/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#include "mmconfig.h"
#include "mmagic_core_data.h"
#include "mmagic_core_ip.h"

/*
 * Maximum allowed length of any value string. Needs to accomodate WLAN password, IP and MAC address
 * strings.
 */
#define MAX_VAL_LEN 101

void mmagic_core_ip_load_all(struct mmagic_data *core)
{
    struct mmagic_ip_data *data = &core->ip_data;
    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("ip.ip_addr", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_struct_ip_addr(&data->config.ip_addr, val);
        }
    }

    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("ip.netmask", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_struct_ip_addr(&data->config.netmask, val);
        }
    }

    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("ip.gateway", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_struct_ip_addr(&data->config.gateway, val);
        }
    }

    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("ip.dns_server0", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_struct_ip_addr(&data->config.dns_server0, val);
        }
    }

    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("ip.dns_server1", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_struct_ip_addr(&data->config.dns_server1, val);
        }
    }

    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("ip.dhcp_enabled", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_bool(&data->config.dhcp_enabled, val);
        }
    }

    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("ip.dhcp_offload", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_bool(&data->config.dhcp_offload, val);
        }
    }

    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("ip.link_status_evt_en", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_bool(&data->config.link_status_evt_en, val);
        }
    }

    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("ip.offload_arp_response", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_bool(&data->config.offload_arp_response, val);
        }
    }

    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("ip.offload_arp_refresh_s", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_uint32_t(&data->config.offload_arp_refresh_s, val);
        }
    }
}

void mmagic_core_ip_save_all(struct mmagic_data *core)
{
    struct mmagic_ip_data *data = &core->ip_data;
    {
        char val[MAX_VAL_LEN];
        mmagic_struct_ip_addr_to_string(&data->config.ip_addr, val, sizeof(val));
        mmconfig_write_string("ip.ip_addr", val);
    }

    {
        char val[MAX_VAL_LEN];
        mmagic_struct_ip_addr_to_string(&data->config.netmask, val, sizeof(val));
        mmconfig_write_string("ip.netmask", val);
    }

    {
        char val[MAX_VAL_LEN];
        mmagic_struct_ip_addr_to_string(&data->config.gateway, val, sizeof(val));
        mmconfig_write_string("ip.gateway", val);
    }

    {
        char val[MAX_VAL_LEN];
        mmagic_struct_ip_addr_to_string(&data->config.dns_server0, val, sizeof(val));
        mmconfig_write_string("ip.dns_server0", val);
    }

    {
        char val[MAX_VAL_LEN];
        mmagic_struct_ip_addr_to_string(&data->config.dns_server1, val, sizeof(val));
        mmconfig_write_string("ip.dns_server1", val);
    }

    {
        char val[MAX_VAL_LEN];
        mmagic_bool_to_string(data->config.dhcp_enabled, val, sizeof(val));
        mmconfig_write_string("ip.dhcp_enabled", val);
    }

    {
        char val[MAX_VAL_LEN];
        mmagic_bool_to_string(data->config.dhcp_offload, val, sizeof(val));
        mmconfig_write_string("ip.dhcp_offload", val);
    }

    {
        char val[MAX_VAL_LEN];
        mmagic_bool_to_string(data->config.link_status_evt_en, val, sizeof(val));
        mmconfig_write_string("ip.link_status_evt_en", val);
    }

    {
        char val[MAX_VAL_LEN];
        mmagic_bool_to_string(data->config.offload_arp_response, val, sizeof(val));
        mmconfig_write_string("ip.offload_arp_response", val);
    }

    {
        char val[MAX_VAL_LEN];
        mmagic_uint32_t_to_string(data->config.offload_arp_refresh_s, val, sizeof(val));
        mmconfig_write_string("ip.offload_arp_refresh_s", val);
    }
}

enum mmagic_status mmagic_core_event_ip_link_status(
    struct mmagic_data *core,
    const struct mmagic_core_event_ip_link_status_args *args)
{
    const uint8_t *payload = (const uint8_t *)args;
    size_t payload_len = sizeof(*args);
    MMOSAL_ASSERT(core->event_fn != NULL);
    return core->event_fn(core->event_fn_arg,
                          mmagic_ip,
                          mmagic_ip_event_link_status,
                          payload,
                          payload_len);
}
