/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#pragma once

#include "mmagic_core_types.h"

struct mmagic_data;

struct mmagic_ping_config
{
    /** The IP address of the ping target. */
    struct struct_ip_addr target;
    /** The time interval between ping requests (in milliseconds). */
    uint32_t interval;
    /** This specifies the number of ping requests to send before terminating the
     * session. If this is zero or exceeds UINT16_MAX (65535) then it it will be set to
     * UINT16_MAX. */
    uint32_t count;
};

struct mmagic_ping_data
{
    struct mmagic_ping_config config;
    /** Subsystem private data (to be allocated/managed by the subsystem implementation). */
    void *priv;
};

/**
 * Function to initialize the core data structure and register the ops functions.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_ping_init(struct mmagic_data *core);

/**
 * Function to load settings from persistent store for the core ping subsystem.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_ping_load_all(struct mmagic_data *core);

/**
 * Function to save settings to persistent store for the core ping subsystem.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_ping_save_all(struct mmagic_data *core);

/**
 * Function to start any of the core processes for the core ping subsystem.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_ping_start(struct mmagic_data *core);

/** Response arguments structure for ping_run */
struct MM_PACKED mmagic_core_ping_run_rsp_args
{
    struct struct_ping_status status;
};

enum mmagic_status mmagic_core_ping_run(struct mmagic_data *core,
                                        struct mmagic_core_ping_run_rsp_args *rsp_args);
