/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#include "mmconfig.h"
#include "mmagic_core_data.h"
#include "mmagic_core_ping.h"

/*
 * Maximum allowed length of any value string. Needs to accomodate WLAN password, IP and MAC address
 * strings.
 */
#define MAX_VAL_LEN 101

void mmagic_core_ping_load_all(struct mmagic_data *core)
{
    struct mmagic_ping_data *data = &core->ping_data;
    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("ping.target", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_struct_ip_addr(&data->config.target, val);
        }
    }

    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("ping.interval", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_uint32_t(&data->config.interval, val);
        }
    }

    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("ping.count", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_uint32_t(&data->config.count, val);
        }
    }
}

void mmagic_core_ping_save_all(struct mmagic_data *core)
{
    struct mmagic_ping_data *data = &core->ping_data;
    {
        char val[MAX_VAL_LEN];
        mmagic_struct_ip_addr_to_string(&data->config.target, val, sizeof(val));
        mmconfig_write_string("ping.target", val);
    }

    {
        char val[MAX_VAL_LEN];
        mmagic_uint32_t_to_string(data->config.interval, val, sizeof(val));
        mmconfig_write_string("ping.interval", val);
    }

    {
        char val[MAX_VAL_LEN];
        mmagic_uint32_t_to_string(data->config.count, val, sizeof(val));
        mmconfig_write_string("ping.count", val);
    }
}
