/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#include "mmconfig.h"
#include "mmagic_core_data.h"
#include "mmagic_core_tls.h"

/*
 * Maximum allowed length of any value string. Needs to accomodate WLAN password, IP and MAC address
 * strings.
 */
#define MAX_VAL_LEN 101

void mmagic_core_tls_load_all(struct mmagic_data *core)
{
    struct mmagic_tls_data *data = &core->tls_data;
    {
        int len = mmconfig_read_bytes("tls.root_ca_certificate",
                                      data->config.root_ca_certificate.data,
                                      sizeof(data->config.root_ca_certificate),
                                      0);
        if (len > 0)
        {
            data->config.root_ca_certificate.len = len;
        }
    }

    {
        int len = mmconfig_read_bytes("tls.client_certificate",
                                      data->config.client_certificate.data,
                                      sizeof(data->config.client_certificate),
                                      0);
        if (len > 0)
        {
            data->config.client_certificate.len = len;
        }
    }

    {
        int len = mmconfig_read_bytes("tls.client_private_key",
                                      data->config.client_private_key.data,
                                      sizeof(data->config.client_private_key),
                                      0);
        if (len > 0)
        {
            data->config.client_private_key.len = len;
        }
    }
}

void mmagic_core_tls_save_all(struct mmagic_data *core)
{
    struct mmagic_tls_data *data = &core->tls_data;
    mmconfig_write_data("tls.root_ca_certificate",
                        data->config.root_ca_certificate.data,
                        data->config.root_ca_certificate.len);

    mmconfig_write_data("tls.client_certificate",
                        data->config.client_certificate.data,
                        data->config.client_certificate.len);

    mmconfig_write_data("tls.client_private_key",
                        data->config.client_private_key.data,
                        data->config.client_private_key.len);
}
