/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#pragma once

#include "mmagic_core_types.h"

struct mmagic_data;

struct mmagic_iperf_config
{
    /** The iperf mode to use. Valid values are udp_server, tcp_server, udp_client and
     * tcp_client. If not set, defaults to udp_server. */
    enum mmagic_iperf_mode mode;
    /** IP address of server to connect to when in client mode. */
    struct struct_ip_addr server;
    /** Specifies the local port to listen on when in server mode or the server port to
     * send data to when in client mode. */
    uint16_t port;
    /** This specifies the duration for client transfers specified either in seconds or
     * bytes. If this is negative, it specifies a time in seconds; if positive, it
     * specifies the number of bytes to transmit. */
    int32_t amount;
};

struct mmagic_iperf_data
{
    struct mmagic_iperf_config config;
    /** Subsystem private data (to be allocated/managed by the subsystem implementation). */
    void *priv;
};

/**
 * Function to initialize the core data structure and register the ops functions.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_iperf_init(struct mmagic_data *core);

/**
 * Function to load settings from persistent store for the core iperf subsystem.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_iperf_load_all(struct mmagic_data *core);

/**
 * Function to save settings to persistent store for the core iperf subsystem.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_iperf_save_all(struct mmagic_data *core);

/**
 * Function to start any of the core processes for the core iperf subsystem.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_iperf_start(struct mmagic_data *core);

/** Response arguments structure for iperf_run */
struct MM_PACKED mmagic_core_iperf_run_rsp_args
{
    struct struct_iperf_status status;
};

enum mmagic_status mmagic_core_iperf_run(struct mmagic_data *core,
                                         struct mmagic_core_iperf_run_rsp_args *rsp_args);
