/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#pragma once

#include "mmagic_core_types.h"

struct mmagic_data;

struct mmagic_wlan_config
{
    /** Two character country code used to identify the regulatory domain. */
    struct struct_country_code country_code;
    /** SSID of the AP to connect to, can be 1-32 characters long. */
    struct string32 ssid;
    /** Password used when associating, 1-100 characters long. */
    struct string100 password;
    /** Security type to used when associating. */
    enum mmagic_security_type security;
    /** Priority to request if raw is supported by the AP. Valid priorities are 0-7. -1
     * disables RAW. */
    int16_t raw_priority;
    /** BSSID of the ap to associate to, all 0x00 for any. */
    struct struct_mac_addr bssid;
    /** Protected Management Frame mode to use (802.11w). */
    enum mmagic_pmf_mode pmf_mode;
    /** S1G non-AP STA type. */
    enum mmagic_station_type station_type;
    /** The RTS threshold (in octets) to set, or 0 to disable. */
    uint32_t rts_threshold;
    /** Boolean value indicating whether SGI support should be enabled. */
    bool sgi_enabled;
    /** Boolean value indicating whether sub-band support should be enabled. */
    bool subbands_enabled;
    /** Boolean value indicating whether AMPDU support should be enabled. */
    bool ampdu_enabled;
    /** Sets the 802.11 power save mode. */
    enum mmagic_power_save_mode power_save_mode;
    /** Sets the 802.11 fragmentation threshold. The fragmentation threshold (in octets)
     * to set, or 0 to disable. */
    uint32_t fragment_threshold;
    /** Whether Centralized Authentication Controlled is enabled on the STA. */
    bool cac_enabled;
    /** The minimum interval to wait after the last health check before triggering
     * another. If this parameter is 0 then health checks will always happen at the
     * max_interval_ms value. min_interval_ms must always be less than or equal to
     * max_interval_ms. If only min_health_check_intvl_ms is specified, then
     * max_health_check_intvl_ms is assumed to be unbounded. */
    uint32_t min_health_check_intvl_ms;
    /** The maximum interval to wait after the last health check before triggering
     * another. If this parameter is 0 then periodic health checks will be disabled.
     * min_interval_ms must always be less than or equal to max_interval_ms. Set this
     * to UINT32_MAX to have the maximum unbounded. If only max_health_check_intvl_ms
     * is specified, then min_health_check_intvl_ms is assumed to be 0. */
    uint32_t max_health_check_intvl_ms;
    /** Boolean value indicating whether NDP probe support should be enabled. Will only
     * take effect after a connect or scan command is sent. */
    bool ndp_probe_enabled;
    /** The base scan interval (in seconds) to use when (re)connecting. See
     * documentation of mmwlan_sta_args.scan_interval_base_s for further details. Note
     * that changes will only take effect on invocation of wlan-connect. */
    uint16_t sta_scan_interval_base_s;
    /** The maximum interval between scan attempts when (re)connecting. See
     * documentation of mmwlan_sta_args.scan_interval_limit_s for further details. Note
     * that changes will only take effect on invocation of wlan-connect. */
    uint16_t sta_scan_interval_limit_s;
    /** The default QoS queue configuration for Access Category 0 (AC_BE) that is active
     * while the station is connecting to an Access Point. This is a string containing
     * the following comma separated integer values (in order):
     * `aifs,cw_min,cw_max,txop_max_us`. For example: `3,15,1023,15008`. More
     * information about the individual parameters can be found in the API
     * documentation for `mmwlan_qos_queue_params`. */
    struct string32 qos_0_params;
    /** The default QoS queue configuration for Access Category 1 (AC_BK) that is active
     * while the station is connecting to an Access Point. This is a string containing
     * the following comma separated integer values (in order):
     * `aifs,cw_min,cw_max,txop_max_us`. For example: `7,15,1023,15008`. More
     * information about the individual parameters can be found in the API
     * documentation for `mmwlan_qos_queue_params`. */
    struct string32 qos_1_params;
    /** The default QoS queue configuration for Access Category 2 (AC_VI) that is active
     * while the station is connecting to an Access Point. This is a string containing
     * the following comma separated integer values (in order):
     * `aifs,cw_min,cw_max,txop_max_us`. For example: `2,7,15,15008`. More information
     * about the individual parameters can be found in the API documentation for
     * `mmwlan_qos_queue_params`. */
    struct string32 qos_2_params;
    /** The default QoS queue configuration for Access Category 3 (AC_VO) that is active
     * while the station is connecting to an Access Point. This is a string containing
     * the following comma separated integer values (in order):
     * `aifs,cw_min,cw_max,txop_max_us`. For example: `2,3,7,15008`. More information
     * about the individual parameters can be found in the API documentation for
     * `mmwlan_qos_queue_params`. */
    struct string32 qos_3_params;
    /** The currently configured MCS10 behavior. This only takes effect after calling
     * the WLAN connect command. This is an enum with 3 modes: disabled, which will
     * never use MCS10, forced, which will always use MCS10 instead of MCS0 if the
     * bandwidth is 1 MHz, and auto, which will use MCS10 on retries instead of MCS0
     * when the bandwidth is 1 MHz. */
    enum mmagic_mcs10_mode mcs10_mode;
    /** When set to true, STA event notifications will be provided. Setting this to
     * false will suppress these notifications. Defaults to false. */
    bool sta_evt_en;
    /** The duty cycle air time distribution mode. The duty cycle mode can be set to
     * spread, where the air time is spread evenly across the window; or burst, where
     * air time is available to be consumed immediately. */
    enum mmagic_duty_cycle_mode duty_cycle_mode;
};

struct mmagic_wlan_data
{
    struct mmagic_wlan_config config;
    /** Subsystem private data (to be allocated/managed by the subsystem implementation). */
    void *priv;
};

/**
 * Function to initialize the core data structure and register the ops functions.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_wlan_init(struct mmagic_data *core);

/**
 * Function to load settings from persistent store for the core wlan subsystem.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_wlan_load_all(struct mmagic_data *core);

/**
 * Function to save settings to persistent store for the core wlan subsystem.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_wlan_save_all(struct mmagic_data *core);

/**
 * Function to start any of the core processes for the core wlan subsystem.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_wlan_start(struct mmagic_data *core);

/** Command arguments structure for wlan_connect */
struct MM_PACKED mmagic_core_wlan_connect_cmd_args
{
    uint32_t timeout;
};

enum mmagic_status mmagic_core_wlan_connect(
    struct mmagic_data *core,
    const struct mmagic_core_wlan_connect_cmd_args *cmd_args);

enum mmagic_status mmagic_core_wlan_disconnect(struct mmagic_data *core);

/** Command arguments structure for wlan_scan */
struct MM_PACKED mmagic_core_wlan_scan_cmd_args
{
    struct string32 ssid;
    uint32_t timeout;
};

/** Response arguments structure for wlan_scan */
struct MM_PACKED mmagic_core_wlan_scan_rsp_args
{
    struct struct_scan_status results;
};

enum mmagic_status mmagic_core_wlan_scan(struct mmagic_data *core,
                                         const struct mmagic_core_wlan_scan_cmd_args *cmd_args,
                                         struct mmagic_core_wlan_scan_rsp_args *rsp_args);

/** Response arguments structure for wlan_get_rssi */
struct MM_PACKED mmagic_core_wlan_get_rssi_rsp_args
{
    int32_t rssi;
};

enum mmagic_status mmagic_core_wlan_get_rssi(struct mmagic_data *core,
                                             struct mmagic_core_wlan_get_rssi_rsp_args *rsp_args);

/** Response arguments structure for wlan_get_mac_addr */
struct MM_PACKED mmagic_core_wlan_get_mac_addr_rsp_args
{
    struct struct_mac_addr mac_addr;
};

enum mmagic_status mmagic_core_wlan_get_mac_addr(
    struct mmagic_data *core,
    struct mmagic_core_wlan_get_mac_addr_rsp_args *rsp_args);

/** Command arguments structure for wlan_wnm_sleep */
struct MM_PACKED mmagic_core_wlan_wnm_sleep_cmd_args
{
    bool wnm_sleep_enabled;
};

enum mmagic_status mmagic_core_wlan_wnm_sleep(
    struct mmagic_data *core,
    const struct mmagic_core_wlan_wnm_sleep_cmd_args *cmd_args);

/** Command arguments structure for wlan_beacon_monitor_enable */
struct MM_PACKED mmagic_core_wlan_beacon_monitor_enable_cmd_args
{
    struct struct_oui_list oui_filter;
};

enum mmagic_status mmagic_core_wlan_beacon_monitor_enable(
    struct mmagic_data *core,
    const struct mmagic_core_wlan_beacon_monitor_enable_cmd_args *cmd_args);

enum mmagic_status mmagic_core_wlan_beacon_monitor_disable(struct mmagic_data *core);

enum mmagic_status mmagic_core_wlan_standby_enter(struct mmagic_data *core);

enum mmagic_status mmagic_core_wlan_standby_exit(struct mmagic_data *core);

/** Command arguments structure for wlan_standby_set_status_payload */
struct MM_PACKED mmagic_core_wlan_standby_set_status_payload_cmd_args
{
    struct struct_buffer64 payload;
};

enum mmagic_status mmagic_core_wlan_standby_set_status_payload(
    struct mmagic_data *core,
    const struct mmagic_core_wlan_standby_set_status_payload_cmd_args *cmd_args);

/** Command arguments structure for wlan_standby_set_wake_filter */
struct MM_PACKED mmagic_core_wlan_standby_set_wake_filter_cmd_args
{
    struct struct_buffer64 filter;
    uint32_t offset;
};

enum mmagic_status mmagic_core_wlan_standby_set_wake_filter(
    struct mmagic_data *core,
    const struct mmagic_core_wlan_standby_set_wake_filter_cmd_args *cmd_args);

/** Command arguments structure for wlan_standby_set_config */
struct MM_PACKED mmagic_core_wlan_standby_set_config_cmd_args
{
    uint32_t notify_period_s;
    struct struct_ip_addr src_ip;
    struct struct_ip_addr dst_ip;
    uint16_t dst_port;
    uint32_t bss_inactivity_s;
    uint32_t snooze_period_s;
    uint32_t snooze_increment_s;
    uint32_t snooze_max_s;
};

enum mmagic_status mmagic_core_wlan_standby_set_config(
    struct mmagic_data *core,
    const struct mmagic_core_wlan_standby_set_config_cmd_args *cmd_args);

/** Response arguments structure for wlan_get_sta_status */
struct MM_PACKED mmagic_core_wlan_get_sta_status_rsp_args
{
    enum mmagic_sta_state sta_status;
};

enum mmagic_status mmagic_core_wlan_get_sta_status(
    struct mmagic_data *core,
    struct mmagic_core_wlan_get_sta_status_rsp_args *rsp_args);

/*
 * ---------------------------------------------------------------------------------------------
 * Internal API: to be used by the implementation C file only.
 * ---------------------------------------------------------------------------------------------
 */

enum mmagic_status mmagic_core_event_wlan_beacon_rx(
    struct mmagic_data *core,
    const struct mmagic_core_event_wlan_beacon_rx_args *args);

enum mmagic_status mmagic_core_event_wlan_standby_exit(
    struct mmagic_data *core,
    const struct mmagic_core_event_wlan_standby_exit_args *args);

enum mmagic_status mmagic_core_event_wlan_sta_event(
    struct mmagic_data *core,
    const struct mmagic_core_event_wlan_sta_event_args *args);
