/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#pragma once

#include "core/autogen/mmagic_core_types.h"

#include "mmagic.h"
#include "mmagic_core_wlan.h"
#include "mmagic_core_ip.h"
#include "mmagic_core_ping.h"
#include "mmagic_core_iperf.h"
#include "mmagic_core_sys.h"
#include "mmagic_core_tcp.h"
#include "mmagic_core_tls.h"
#include "mmagic_core_ntp.h"
#include "mmagic_core_mqtt.h"

/** Maximum length of the @c app_version string (excluding null terminator). */
#define MMAGIC_SYS_MAX_APP_VERSION_LENGTH (31)

/** Maximum number of streams we support in MMAGIC */
#define MMAGIC_MAX_STREAMS 8

/**
 * Function type for M2M/CLI-specific event implementation.
 *
 * @param core          MMAGIC core data structure.
 * @param payload       Event payload.
 * @param payload_len   Length of the event payload.
 */
typedef enum mmagic_status (*mmagic_event_fn_t)(void *arg,
                                                uint8_t subsystem_id,
                                                uint8_t event_id,
                                                const uint8_t *payload,
                                                size_t payload_len);

/** mmagic core data structure. */
struct mmagic_data
{
    struct mmagic_wlan_data wlan_data;
    struct mmagic_ip_data ip_data;
    struct mmagic_ping_data ping_data;
    struct mmagic_iperf_data iperf_data;
    struct mmagic_sys_data sys_data;
    struct mmagic_tcp_data tcp_data;
    struct mmagic_tls_data tls_data;
    struct mmagic_ntp_data ntp_data;
    struct mmagic_mqtt_data mqtt_data;

    /** Reference to the regulatory database */
    const struct mmwlan_regulatory_db *reg_db;

    /** Application version string. This is a null terminated string. */
    char app_version[MMAGIC_SYS_MAX_APP_VERSION_LENGTH + 1];

    /** Stream context for each stream. */
    struct mmagic_m2m_stream *stream[MMAGIC_MAX_STREAMS];

    /** Opaque arg to pass to @c set_deep_sleep_mode_cb. */
    void *set_deep_sleep_mode_cb_arg;
    /** Set deep sleep mode callback */
    mmagic_set_deep_sleep_mode_cb_t set_deep_sleep_mode_cb;

    /** Event processing function implementation. */
    mmagic_event_fn_t event_fn;
    /** Opaque argument for the event implementation. */
    void *event_fn_arg;
};

static inline struct mmagic_wlan_data *mmagic_data_get_wlan(struct mmagic_data *core)
{
    return &core->wlan_data;
}

static inline struct mmagic_ip_data *mmagic_data_get_ip(struct mmagic_data *core)
{
    return &core->ip_data;
}

static inline struct mmagic_ping_data *mmagic_data_get_ping(struct mmagic_data *core)
{
    return &core->ping_data;
}

static inline struct mmagic_iperf_data *mmagic_data_get_iperf(struct mmagic_data *core)
{
    return &core->iperf_data;
}

static inline struct mmagic_sys_data *mmagic_data_get_sys(struct mmagic_data *core)
{
    return &core->sys_data;
}

static inline struct mmagic_tcp_data *mmagic_data_get_tcp(struct mmagic_data *core)
{
    return &core->tcp_data;
}

static inline struct mmagic_tls_data *mmagic_data_get_tls(struct mmagic_data *core)
{
    return &core->tls_data;
}

static inline struct mmagic_ntp_data *mmagic_data_get_ntp(struct mmagic_data *core)
{
    return &core->ntp_data;
}

static inline struct mmagic_mqtt_data *mmagic_data_get_mqtt(struct mmagic_data *core)
{
    return &core->mqtt_data;
}

void mmagic_core_init_modules(struct mmagic_data *mmagicd);
