/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#include "mmconfig.h"
#include "mmagic_core_data.h"
#include "mmagic_core_iperf.h"

/*
 * Maximum allowed length of any value string. Needs to accomodate WLAN password, IP and MAC address
 * strings.
 */
#define MAX_VAL_LEN 101

void mmagic_core_iperf_load_all(struct mmagic_data *core)
{
    struct mmagic_iperf_data *data = &core->iperf_data;
    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("iperf.mode", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_enum_iperf_mode(&data->config.mode, val);
        }
    }

    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("iperf.server", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_struct_ip_addr(&data->config.server, val);
        }
    }

    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("iperf.port", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_uint16_t(&data->config.port, val);
        }
    }

    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("iperf.amount", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_int32_t(&data->config.amount, val);
        }
    }
}

void mmagic_core_iperf_save_all(struct mmagic_data *core)
{
    struct mmagic_iperf_data *data = &core->iperf_data;
    {
        char val[MAX_VAL_LEN];
        mmagic_enum_iperf_mode_to_string(data->config.mode, val, sizeof(val));
        mmconfig_write_string("iperf.mode", val);
    }

    {
        char val[MAX_VAL_LEN];
        mmagic_struct_ip_addr_to_string(&data->config.server, val, sizeof(val));
        mmconfig_write_string("iperf.server", val);
    }

    {
        char val[MAX_VAL_LEN];
        mmagic_uint16_t_to_string(data->config.port, val, sizeof(val));
        mmconfig_write_string("iperf.port", val);
    }

    {
        char val[MAX_VAL_LEN];
        mmagic_int32_t_to_string(data->config.amount, val, sizeof(val));
        mmconfig_write_string("iperf.amount", val);
    }
}
