/*
 * Copyright 2024 Morse Micro
 *
 * This file is licensed under terms that can be found in the LICENSE.md file in the root
 * directory of the Morse Micro IoT SDK software package.
 */

#pragma once

/**
 * Root certificate from Google trust services.
 *
 * @code
 * https://pki.goog/repository/
 *
 * Certificate:
 *     Data:
 *         Version: 3 (0x2)
 *         Serial Number:
 *             02:03:e5:93:6f:31:b0:13:49:88:6b:a2:17
 *         Signature Algorithm: sha384WithRSAEncryption
 *         Issuer: C = US, O = Google Trust Services LLC, CN = GTS Root R1
 *         Validity
 *             Not Before: Jun 22 00:00:00 2016 GMT
 *             Not After : Jun 22 00:00:00 2036 GMT
 *         Subject: C = US, O = Google Trust Services LLC, CN = GTS Root R1
 *  @endcode
 */
#define DEFAULT_ROOT_CERT                                                  \
    "-----BEGIN CERTIFICATE-----\r\n"                                      \
    "MIIFVzCCAz+gAwIBAgINAgPlk28xsBNJiGuiFzANBgkqhkiG9w0BAQwFADBHMQsw\r\n" \
    "CQYDVQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZpY2VzIExMQzEU\r\n" \
    "MBIGA1UEAxMLR1RTIFJvb3QgUjEwHhcNMTYwNjIyMDAwMDAwWhcNMzYwNjIyMDAw\r\n" \
    "MDAwWjBHMQswCQYDVQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZp\r\n" \
    "Y2VzIExMQzEUMBIGA1UEAxMLR1RTIFJvb3QgUjEwggIiMA0GCSqGSIb3DQEBAQUA\r\n" \
    "A4ICDwAwggIKAoICAQC2EQKLHuOhd5s73L+UPreVp0A8of2C+X0yBoJx9vaMf/vo\r\n" \
    "27xqLpeXo4xL+Sv2sfnOhB2x+cWX3u+58qPpvBKJXqeqUqv4IyfLpLGcY9vXmX7w\r\n" \
    "Cl7raKb0xlpHDU0QM+NOsROjyBhsS+z8CZDfnWQpJSMHobTSPS5g4M/SCYe7zUjw\r\n" \
    "TcLCeoiKu7rPWRnWr4+wB7CeMfGCwcDfLqZtbBkOtdh+JhpFAz2weaSUKK0Pfybl\r\n" \
    "qAj+lug8aJRT7oM6iCsVlgmy4HqMLnXWnOunVmSPlk9orj2XwoSPwLxAwAtcvfaH\r\n" \
    "szVsrBhQf4TgTM2S0yDpM7xSma8ytSmzJSq0SPly4cpk9+aCEI3oncKKiPo4Zor8\r\n" \
    "Y/kB+Xj9e1x3+naH+uzfsQ55lVe0vSbv1gHR6xYKu44LtcXFilWr06zqkUspzBmk\r\n" \
    "MiVOKvFlRNACzqrOSbTqn3yDsEB750Orp2yjj32JgfpMpf/VjsPOS+C12LOORc92\r\n" \
    "wO1AK/1TD7Cn1TsNsYqiA94xrcx36m97PtbfkSIS5r762DL8EGMUUXLeXdYWk70p\r\n" \
    "aDPvOmbsB4om3xPXV2V4J95eSRQAogB/mqghtqmxlbCluQ0WEdrHbEg8QOB+DVrN\r\n" \
    "VjzRlwW5y0vtOUucxD/SVRNuJLDWcfr0wbrM7Rv1/oFB2ACYPTrIrnqYNxgFlQID\r\n" \
    "AQABo0IwQDAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4E\r\n" \
    "FgQU5K8rJnEaK0gnhS9SZizv8IkTcT4wDQYJKoZIhvcNAQEMBQADggIBAJ+qQibb\r\n" \
    "C5u+/x6Wki4+omVKapi6Ist9wTrYggoGxval3sBOh2Z5ofmmWJyq+bXmYOfg6LEe\r\n" \
    "QkEzCzc9zolwFcq1JKjPa7XSQCGYzyI0zzvFIoTgxQ6KfF2I5DUkzps+GlQebtuy\r\n" \
    "h6f88/qBVRRiClmpIgUxPoLW7ttXNLwzldMXG+gnoot7TiYaelpkttGsN/H9oPM4\r\n" \
    "7HLwEXWdyzRSjeZ2axfG34arJ45JK3VmgRAhpuo+9K4l/3wV3s6MJT/KYnAK9y8J\r\n" \
    "ZgfIPxz88NtFMN9iiMG1D53Dn0reWVlHxYciNuaCp+0KueIHoI17eko8cdLiA6Ef\r\n" \
    "MgfdG+RCzgwARWGAtQsgWSl4vflVy2PFPEz0tv/bal8xa5meLMFrUKTX5hgUvYU/\r\n" \
    "Z6tGn6D/Qqc6f1zLXbBwHSs09dR2CQzreExZBfMzQsNhFRAbd03OIozUhfJFfbdT\r\n" \
    "6u9AWpQKXCBfTkBdYiJ23//OYb2MI3jSNwLgjt7RETeJ9r/tSQdirpLsQBqvFAnZ\r\n" \
    "0E6yove+7u7Y/9waLd64NnHi/Hm3lCXRSHNboTXns5lndcEZOitHTtNCjv0xyBZm\r\n" \
    "2tIMPNuzjsmhDYAPexZ3FL//2wmUspO8IFgV6dtxQ/PeEMMA3KgqlbbC1j+Qa3bb\r\n" \
    "bP6MvPJwNQzcmRk13NfIRmPVNnGuV/u3gm3c\r\n"                             \
    "-----END CERTIFICATE-----\r\n"

/**
 * Client key used for testing purposes.
 *
 * Generated by running:
 * @code
 * openssl genrsa 2048 -out sslclient.key
 * @endcode
 */
#define DEFAULT_CLIENT_KEY                                                 \
    "-----BEGIN PRIVATE KEY-----\r\n"                                      \
    "MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDGp9LLKRLAuziG\r\n" \
    "2GzX6zhXWJR2PEOw+XiAOKBmy8wDC/IN5+w/eRXJSue9QtIZ9J94Y7m4XXTUkuTK\r\n" \
    "ia1pT6PLKCnrBXBUip/Fqt88ROlvyMqXDAM3qhCOQ0aiO1AJLzqAURJQucXpFPj9\r\n" \
    "uAZAmL7eJ+gZ2f27NIhE9XtW5UdZNqJ9yzSXLIDm/BYrW+5kzW1Q8/QMlOAK+IPr\r\n" \
    "NCY0eS8dgi7Z2kEaVLCm4aEjgp5R8GCXTo+rbBJdRVTpFi3admeI0TVu4cMYl4WR\r\n" \
    "NQYJ76sQ9O1jxRVXKMDVXWfzwrb9/qbUY4iSUIWKGVK9o9xeKGKjnU11ClaXw+ee\r\n" \
    "F0BaoYO/AgMBAAECggEABxzaKMkDMWBisT1NhFuZLFNxGVymBc+g12Jvp86TMua6\r\n" \
    "F3Je3JTuyULD0lxynlhKX2qeqzG5baUGyROt4E/oKu14tr/+miBOgSrRjFxhSU3U\r\n" \
    "pxzYfqU5q4ZQIJ3kCzgkLZT5hWdpZSOJmLf+jVCKwPSH1GkgMxQ57tIlROK3r8N7\r\n" \
    "TsQqk7/SpSd4zgoAJbF6nV0eFYb7G39BV3CWNITVjUcMrxuRkh/70NfctzwcJi38\r\n" \
    "b8ENECezSvRZ/ewofP0jnVYpu7RR2x5uxbddbx1xLOEYjP7oTHi7jncRCn3QwdPR\r\n" \
    "U3U4hqH0mcdRX5bXjUQChBnhanKObYryadpWnDzROQKBgQD2R4fb02mJftaT9YrI\r\n" \
    "2leT28QUAAKmWK7HaVTutv2rJUcDnrxzghT3gSF9fWjFuMYsoYIh7ppIvMDkRiIj\r\n" \
    "xs+UDaA5nYbtLXCTslYfgUfb9rk1ccxAM9x3GPh5Hpf+b+koIRxYzZ6WNEkC4WJk\r\n" \
    "wQmGcc0F5OHXltFSDouwzkELRwKBgQDOfxbaAFJ/Sq1XR1k6FbYFOTZDXh2HmGRf\r\n" \
    "wI6TuLgAxC4Uy0NCTyWZvvXPMiXqBcIARpZj5W4Tvh8zyL1WDEYLV6ZB0a0k267k\r\n" \
    "wzL/ytZcyVyQmup0N4hKCqi8sg2CiRyfyBxd/NQOrPAY/m9F9k1OMMnXQ8rLQLq7\r\n" \
    "AN8GdSWPyQKBgQCRKaZtrxZE4gtOmOtd6jy2vVG8zCjDrgAPMAnMzvWEPGu4OYcw\r\n" \
    "ulrrbCS2WAY6jOfahLQ0lfRArWkw5BnZZqURylpHu489G4yAshxLY6NchveyBcpz\r\n" \
    "iV4IoSJMGflTEtmmOqX/vesc8+KZHQonAxU/NrK3J6rqrU3iBQrXgysZnwKBgQCL\r\n" \
    "/RJz1dYXn3ul+KOfwgo0vlVwFES2oPQjCbpeoNJ1Coom5KmDMX7PHOstfNTBMwgT\r\n" \
    "AceAj5AxaCllBMh+pjFyDQiUBF5550hIo6BWUp9CJexPyAX7pY4Ki/FaguavwN4b\r\n" \
    "4CCDAxyLmmfmuc6bwl8kC+U5vyai5g3xKqUHjrFZKQKBgQDVa+ZRFmdJD9TN5T5/\r\n" \
    "MQ2C7E5LizY4FzjYMh5t3loYiOnN3L1IX+gQKgszJwMqBr7woSwux7tszgA12YO5\r\n" \
    "AUrqrBTMMv0wrN15N/COdTrmZkHL5Masr4NPmEJSfO8CWWrtVZRGWFwNOXDC0bjB\r\n" \
    "7Fb+BuR9AmrrK2XAFJTZtjQpQg==\r\n"                                     \
    "-----END PRIVATE KEY-----\r\n"

/**
 * Client certificate used for testing purposes.
 *
 * Generated by running:
 * @code
 * openssl req -new -x509 -days 36500 -key sslclient.key -out sslclient.crt
 * @endcode
 */
#define DEFAULT_CLIENT_CERT                                                \
    "-----BEGIN CERTIFICATE-----\r\n"                                      \
    "MIIDbTCCAlWgAwIBAgIUNz6EJKw8VoRI5pbEPqXrmXyLqNkwDQYJKoZIhvcNAQEL\r\n" \
    "BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM\r\n" \
    "GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAgFw0yNDExMDUwMjIzMTJaGA8yMTI0\r\n" \
    "MTAxMjAyMjMxMlowRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUx\r\n" \
    "ITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDCCASIwDQYJKoZIhvcN\r\n" \
    "AQEBBQADggEPADCCAQoCggEBAMan0sspEsC7OIbYbNfrOFdYlHY8Q7D5eIA4oGbL\r\n" \
    "zAML8g3n7D95FclK571C0hn0n3hjubhddNSS5MqJrWlPo8soKesFcFSKn8Wq3zxE\r\n" \
    "6W/IypcMAzeqEI5DRqI7UAkvOoBRElC5xekU+P24BkCYvt4n6BnZ/bs0iET1e1bl\r\n" \
    "R1k2on3LNJcsgOb8Fitb7mTNbVDz9AyU4Ar4g+s0JjR5Lx2CLtnaQRpUsKbhoSOC\r\n" \
    "nlHwYJdOj6tsEl1FVOkWLdp2Z4jRNW7hwxiXhZE1BgnvqxD07WPFFVcowNVdZ/PC\r\n" \
    "tv3+ptRjiJJQhYoZUr2j3F4oYqOdTXUKVpfD554XQFqhg78CAwEAAaNTMFEwHQYD\r\n" \
    "VR0OBBYEFCPYQrz6gqXUN1dnwwzUSIkpdnTdMB8GA1UdIwQYMBaAFCPYQrz6gqXU\r\n" \
    "N1dnwwzUSIkpdnTdMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB\r\n" \
    "AEV0ecj/DSmthqDoFA3K3BYDWfk9ONHZTEfIziE9k+TQ2K+bkrG6JCT7gWQ9BIm5\r\n" \
    "0EY/H1YtepIu2wNNGxdUnhHP4pR5CIhgBg2UHu48DPfZX4KoE7DZQb11pXEm/i4Y\r\n" \
    "lXALJJQ5TtDcWX8wIOs5OdBCYvqbS+OUr+21divvFbjLQ3mzhZlA4KZ6C4c7Hfgx\r\n" \
    "SswKYN6f+KKq3StMphM818Z0xplN2KD6cVrpYW6NPVx8YDzLmvFFqQ0clkTb/Jpr\r\n" \
    "01FVRSyNjQWvwg9ddAZgPhoifXdvbMJOEOvagRMpESo73sS1NHhhiYV1YECuuwcJ\r\n" \
    "Am7evuBNtJ8vgkgYvXXFXXM=\r\n"                                         \
    "-----END CERTIFICATE-----\r\n"
