/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#pragma once

#include <stddef.h>
#include <stdio.h>

#include "mmbuf.h"
#include "core/autogen/mmagic_core_data.h"
#include "m2m_api/autogen/mmagic_m2m_wlan.h"
#include "m2m_api/autogen/mmagic_m2m_ip.h"
#include "m2m_api/autogen/mmagic_m2m_ping.h"
#include "m2m_api/autogen/mmagic_m2m_iperf.h"
#include "m2m_api/autogen/mmagic_m2m_sys.h"
#include "m2m_api/autogen/mmagic_m2m_tcp.h"
#include "m2m_api/autogen/mmagic_m2m_tls.h"
#include "m2m_api/autogen/mmagic_m2m_ntp.h"
#include "m2m_api/autogen/mmagic_m2m_mqtt.h"

/**
 * Process the received M2M buffer.
 *
 * @param ctx           Reference to the global mmagic data structure.
 * @param sid     The stream ID this buffer was received on.
 * @param header        The M2M header containing the subsystem, command and subcommand.
 * @param cmd_buf       The @c mmbuf with the buffer to be processed.
 * @return              An @c mmbuf with the response.
 */
struct mmbuf *mmagic_m2m_process(struct mmagic_m2m_agent *agent,
                                 uint8_t sid,
                                 struct mmagic_m2m_command_header *header,
                                 struct mmbuf *cmd_buf);
