/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#pragma once

#include "core/autogen/mmagic_core_data.h"
#include "m2m_api/mmagic_m2m_agent.h"

/********* Enumerations **********/
enum mmagic_ip_vars
{
    mmagic_ip_var_ip_addr = 0,
    mmagic_ip_var_netmask = 1,
    mmagic_ip_var_gateway = 2,
    mmagic_ip_var_dns_server0 = 3,
    mmagic_ip_var_dns_server1 = 4,
    mmagic_ip_var_dhcp_enabled = 5,
    mmagic_ip_var_dhcp_offload = 6,
    mmagic_ip_var_link_status_evt_en = 7,
    mmagic_ip_var_offload_arp_response = 8,
    mmagic_ip_var_offload_arp_refresh_s = 9,
};

/**
 * Process the received M2M buffer.
 *
 * @param agent         Reference to the M2M Agent context.
 * @param sid           The stream ID this buffer was received on.
 * @param header        The M2M header containing the subsystem, command and subcommand.
 * @param cmd_buf       The @c mmbuf with the buffer to be processed.
 * @return              An @c mmbuf with the response.
 */
struct mmbuf *mmagic_m2m_ip_process(struct mmagic_m2m_agent *agent,
                                    uint8_t sid,
                                    struct mmagic_m2m_command_header *header,
                                    struct mmbuf *cmd_buf);
