/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#include "mmagic_m2m_internal.h"

struct mmbuf *mmagic_m2m_process(struct mmagic_m2m_agent *agent,
                                 uint8_t sid,
                                 struct mmagic_m2m_command_header *header,
                                 struct mmbuf *cmd_buf)
{
    switch (header->subsystem)
    {
        case mmagic_wlan:
            return mmagic_m2m_wlan_process(agent, sid, header, cmd_buf);

        case mmagic_ip:
            return mmagic_m2m_ip_process(agent, sid, header, cmd_buf);

        case mmagic_ping:
            return mmagic_m2m_ping_process(agent, sid, header, cmd_buf);

        case mmagic_iperf:
            return mmagic_m2m_iperf_process(agent, sid, header, cmd_buf);

        case mmagic_sys:
            return mmagic_m2m_sys_process(agent, sid, header, cmd_buf);

        case mmagic_tcp:
            return mmagic_m2m_tcp_process(agent, sid, header, cmd_buf);

        case mmagic_tls:
            return mmagic_m2m_tls_process(agent, sid, header, cmd_buf);

        case mmagic_ntp:
            return mmagic_m2m_ntp_process(agent, sid, header, cmd_buf);

        case mmagic_mqtt:
            return mmagic_m2m_mqtt_process(agent, sid, header, cmd_buf);

        default:
            return mmagic_m2m_create_response(header->subsystem,
                                              header->command,
                                              header->subcommand,
                                              MMAGIC_STATUS_NOT_FOUND,
                                              NULL,
                                              0);
    }
}
