/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 *
 * Note: The corresponding headers files must be included BEFORE this def file. Additionally this
 *       file should only be in one (and only one) compilation unit (.c/.cpp file).
 */

#include "mmconfig.h"
#include "mmutils.h"
#include "core/autogen/mmagic_core_mqtt.h"
#include "core/autogen/mmagic_core_types.h"
#include "m2m_api/autogen/mmagic_m2m_mqtt.h"
#include "m2m_api/autogen/mmagic_m2m_internal.h"
#include "m2m_api/mmagic_m2m_agent.h"

/* Maximum allowed length of any value string, needs to accomodate IP and MAC address strings */
#define MAX_VAL_LEN 32

/********* M2M Command Handlers **********/

static struct mmbuf *mmagic_m2m_mqtt_start_agent(struct mmagic_m2m_agent *agent,
                                                 uint8_t sid,
                                                 uint8_t subcommand,
                                                 struct mmbuf *commandbuffer)
{
    enum mmagic_status status;
    struct mmagic_core_mqtt_start_agent_cmd_args *cmd_args =
        (struct mmagic_core_mqtt_start_agent_cmd_args *)mmbuf_get_data_start(commandbuffer);
    MM_UNUSED(sid);
    struct mmagic_core_mqtt_start_agent_rsp_args rsp_args = {};
    status = mmagic_core_mqtt_start_agent(&agent->core, cmd_args, &rsp_args);
    return mmagic_m2m_create_response(mmagic_mqtt,
                                      mmagic_mqtt_cmd_start_agent,
                                      subcommand,
                                      status,
                                      &rsp_args,
                                      sizeof(rsp_args));
}

static struct mmbuf *mmagic_m2m_mqtt_publish(struct mmagic_m2m_agent *agent,
                                             uint8_t sid,
                                             uint8_t subcommand,
                                             struct mmbuf *commandbuffer)
{
    enum mmagic_status status;
    struct mmagic_core_mqtt_publish_cmd_args *cmd_args =
        (struct mmagic_core_mqtt_publish_cmd_args *)mmbuf_get_data_start(commandbuffer);
    MM_UNUSED(sid);
    status = mmagic_core_mqtt_publish(&agent->core, cmd_args);
    return mmagic_m2m_create_response(mmagic_mqtt,
                                      mmagic_mqtt_cmd_publish,
                                      subcommand,
                                      status,
                                      NULL,
                                      0);
}

static struct mmbuf *mmagic_m2m_mqtt_subscribe(struct mmagic_m2m_agent *agent,
                                               uint8_t sid,
                                               uint8_t subcommand,
                                               struct mmbuf *commandbuffer)
{
    enum mmagic_status status;
    struct mmagic_core_mqtt_subscribe_cmd_args *cmd_args =
        (struct mmagic_core_mqtt_subscribe_cmd_args *)mmbuf_get_data_start(commandbuffer);
    MM_UNUSED(sid);
    status = mmagic_core_mqtt_subscribe(&agent->core, cmd_args);
    return mmagic_m2m_create_response(mmagic_mqtt,
                                      mmagic_mqtt_cmd_subscribe,
                                      subcommand,
                                      status,
                                      NULL,
                                      0);
}

static struct mmbuf *mmagic_m2m_mqtt_stop_agent(struct mmagic_m2m_agent *agent,
                                                uint8_t sid,
                                                uint8_t subcommand,
                                                struct mmbuf *commandbuffer)
{
    enum mmagic_status status;
    struct mmagic_core_mqtt_stop_agent_cmd_args *cmd_args =
        (struct mmagic_core_mqtt_stop_agent_cmd_args *)mmbuf_get_data_start(commandbuffer);
    MM_UNUSED(sid);
    status = mmagic_core_mqtt_stop_agent(&agent->core, cmd_args);
    return mmagic_m2m_create_response(mmagic_mqtt,
                                      mmagic_mqtt_cmd_stop_agent,
                                      subcommand,
                                      status,
                                      NULL,
                                      0);
}

struct mmbuf *mmagic_m2m_mqtt_process(struct mmagic_m2m_agent *agent,
                                      uint8_t sid,
                                      struct mmagic_m2m_command_header *header,
                                      struct mmbuf *cmd_buf)
{
    if (header)
    {
        switch (header->command)
        {
            case mmagic_mqtt_cmd_start_agent:
                return mmagic_m2m_mqtt_start_agent(agent, sid, header->subcommand, cmd_buf);
                break;

            case mmagic_mqtt_cmd_publish:
                return mmagic_m2m_mqtt_publish(agent, sid, header->subcommand, cmd_buf);
                break;

            case mmagic_mqtt_cmd_subscribe:
                return mmagic_m2m_mqtt_subscribe(agent, sid, header->subcommand, cmd_buf);
                break;

            case mmagic_mqtt_cmd_stop_agent:
                return mmagic_m2m_mqtt_stop_agent(agent, sid, header->subcommand, cmd_buf);
                break;

            default:
                return mmagic_m2m_create_response(header->subsystem,
                                                  header->command,
                                                  header->subcommand,
                                                  MMAGIC_STATUS_NOT_SUPPORTED,
                                                  NULL,
                                                  0);
        }
    }
    else
    {
        return mmagic_m2m_create_response(0, 0, 0, MMAGIC_STATUS_ERROR, NULL, 0);
    }
}
