/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 *
 * Note: The corresponding headers files must be included BEFORE this def file. Additionally this
 *       file should only be in one (and only one) compilation unit (.c/.cpp file).
 */

#include "mmconfig.h"
#include "mmutils.h"
#include "core/autogen/mmagic_core_sys.h"
#include "core/autogen/mmagic_core_types.h"
#include "m2m_api/autogen/mmagic_m2m_sys.h"
#include "m2m_api/autogen/mmagic_m2m_internal.h"
#include "m2m_api/mmagic_m2m_agent.h"

/* Maximum allowed length of any value string, needs to accomodate IP and MAC address strings */
#define MAX_VAL_LEN 32

/********* M2M Command Handlers **********/

static struct mmbuf *mmagic_m2m_sys_reset(struct mmagic_m2m_agent *agent,
                                          uint8_t sid,
                                          uint8_t subcommand,
                                          struct mmbuf *commandbuffer)
{
    enum mmagic_status status;
    MM_UNUSED(commandbuffer);
    MM_UNUSED(sid);
    status = mmagic_core_sys_reset(&agent->core);
    return mmagic_m2m_create_response(mmagic_sys,
                                      mmagic_sys_cmd_reset,
                                      subcommand,
                                      status,
                                      NULL,
                                      0);
}

static struct mmbuf *mmagic_m2m_sys_deep_sleep(struct mmagic_m2m_agent *agent,
                                               uint8_t sid,
                                               uint8_t subcommand,
                                               struct mmbuf *commandbuffer)
{
    enum mmagic_status status;
    struct mmagic_core_sys_deep_sleep_cmd_args *cmd_args =
        (struct mmagic_core_sys_deep_sleep_cmd_args *)mmbuf_get_data_start(commandbuffer);
    MM_UNUSED(sid);
    status = mmagic_core_sys_deep_sleep(&agent->core, cmd_args);
    return mmagic_m2m_create_response(mmagic_sys,
                                      mmagic_sys_cmd_deep_sleep,
                                      subcommand,
                                      status,
                                      NULL,
                                      0);
}

static struct mmbuf *mmagic_m2m_sys_get_version(struct mmagic_m2m_agent *agent,
                                                uint8_t sid,
                                                uint8_t subcommand,
                                                struct mmbuf *commandbuffer)
{
    enum mmagic_status status;
    MM_UNUSED(commandbuffer);
    MM_UNUSED(sid);
    struct mmagic_core_sys_get_version_rsp_args rsp_args = {};
    status = mmagic_core_sys_get_version(&agent->core, &rsp_args);
    return mmagic_m2m_create_response(mmagic_sys,
                                      mmagic_sys_cmd_get_version,
                                      subcommand,
                                      status,
                                      &rsp_args,
                                      sizeof(rsp_args));
}

struct mmbuf *mmagic_m2m_sys_process(struct mmagic_m2m_agent *agent,
                                     uint8_t sid,
                                     struct mmagic_m2m_command_header *header,
                                     struct mmbuf *cmd_buf)
{
    if (header)
    {
        switch (header->command)
        {
            case mmagic_sys_cmd_reset:
                return mmagic_m2m_sys_reset(agent, sid, header->subcommand, cmd_buf);
                break;

            case mmagic_sys_cmd_deep_sleep:
                return mmagic_m2m_sys_deep_sleep(agent, sid, header->subcommand, cmd_buf);
                break;

            case mmagic_sys_cmd_get_version:
                return mmagic_m2m_sys_get_version(agent, sid, header->subcommand, cmd_buf);
                break;

            default:
                return mmagic_m2m_create_response(header->subsystem,
                                                  header->command,
                                                  header->subcommand,
                                                  MMAGIC_STATUS_NOT_SUPPORTED,
                                                  NULL,
                                                  0);
        }
    }
    else
    {
        return mmagic_m2m_create_response(0, 0, 0, MMAGIC_STATUS_ERROR, NULL, 0);
    }
}
