/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#pragma once

#include "core/autogen/mmagic_core_data.h"
#include "m2m_api/mmagic_m2m_agent.h"

/********* Enumerations **********/
enum mmagic_iperf_vars
{
    mmagic_iperf_var_mode = 0,
    mmagic_iperf_var_server = 1,
    mmagic_iperf_var_port = 2,
    mmagic_iperf_var_amount = 3,
};

/**
 * Process the received M2M buffer.
 *
 * @param agent         Reference to the M2M Agent context.
 * @param sid           The stream ID this buffer was received on.
 * @param header        The M2M header containing the subsystem, command and subcommand.
 * @param cmd_buf       The @c mmbuf with the buffer to be processed.
 * @return              An @c mmbuf with the response.
 */
struct mmbuf *mmagic_m2m_iperf_process(struct mmagic_m2m_agent *agent,
                                       uint8_t sid,
                                       struct mmagic_m2m_command_header *header,
                                       struct mmbuf *cmd_buf);
