/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */
#include "mmagic_cli_wlan.h"
#include "mmagic_cli_ip.h"
#include "mmagic_cli_ping.h"
#include "mmagic_cli_iperf.h"
#include "mmagic_cli_sys.h"

void mmagic_cli_init_modules(struct mmagic_cli *ctx)
{
    mmagic_cli_wlan_init(ctx);

    mmagic_cli_ip_init(ctx);

    mmagic_cli_ping_init(ctx);

    mmagic_cli_iperf_init(ctx);

    mmagic_cli_sys_init(ctx);
};

enum mmagic_status mmagic_cli_handle_event(void *arg,
                                           uint8_t subsystem_id,
                                           uint8_t event_id,
                                           const uint8_t *payload,
                                           size_t payload_len)
{
    struct mmagic_cli *ctx = (struct mmagic_cli *)arg;

    /* This is from autogenerated code so it is relatively safe to assume payload_len is correct. */
    MM_UNUSED(payload_len);

    switch (subsystem_id)
    {
        case mmagic_wlan:
            switch (event_id)
            {
                case mmagic_wlan_event_beacon_rx:
                    mmagic_cli_wlan_handle_event_beacon_rx(
                        ctx,
                        (const struct mmagic_core_event_wlan_beacon_rx_args *)payload);
                    return MMAGIC_STATUS_OK;
                case mmagic_wlan_event_standby_exit:
                    mmagic_cli_wlan_handle_event_standby_exit(
                        ctx,
                        (const struct mmagic_core_event_wlan_standby_exit_args *)payload);
                    return MMAGIC_STATUS_OK;
                case mmagic_wlan_event_sta_event:
                    mmagic_cli_wlan_handle_event_sta_event(
                        ctx,
                        (const struct mmagic_core_event_wlan_sta_event_args *)payload);
                    return MMAGIC_STATUS_OK;

                default:
                    break;
            }
            break;
        case mmagic_ip:
            switch (event_id)
            {
                case mmagic_ip_event_link_status:
                    mmagic_cli_ip_handle_event_link_status(
                        ctx,
                        (const struct mmagic_core_event_ip_link_status_args *)payload);
                    return MMAGIC_STATUS_OK;

                default:
                    break;
            }
            break;

        default:
            break;
    }

    /* If we get here this indicates programming error since this should only be invoked
     * from autogenerated code. */
    MMOSAL_ASSERT(false);
    return MMAGIC_STATUS_INVALID_ARG;
}
