/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 *
 * Note: The corresponding headers files must be included BEFORE this def file. Additionally this
 *       file should only be in one (and only one) compilation unit (.c/.cpp file).
 */
#include <ctype.h>

#include "mmconfig.h"
#include "mmutils.h"
#include "cli/mmagic_cli.h"
#include "cli/autogen/mmagic_cli_internal.h"

/*
 * The fixed width that the key will be padded to, with trailing spaces, before the value is
 * printed.
 */
#define KEY_NAME_PADDING 32

/********* Getters **********/

int mmagic_cli_iperf_get_mode(struct mmagic_data *core, EmbeddedCli *cli)
{
    struct mmagic_iperf_data *data = mmagic_data_get_iperf(core);
    const char *key_name = "iperf.mode";
    MM_STATIC_ASSERT((sizeof("iperf.mode") - 1) < KEY_NAME_PADDING,
                     "Key must be shorter than padding");

    char buf[MMAGIC_CLI_PRINT_BUF_LEN] = { 0 };
    /* -1 to allow for a NULL terminator at the end */
    const size_t max_str_len = sizeof(buf) - 1;
    size_t cursor = 0;
    int written = 0;

    written = snprintf(&buf[cursor], max_str_len - cursor, "%-*s", KEY_NAME_PADDING, key_name);
    if (written < 0 || (cursor + written) > max_str_len)
    {
        return -1;
    }
    cursor += written;
    written =
        mmagic_enum_iperf_mode_to_string(data->config.mode, &buf[cursor], max_str_len - cursor);
    if (written == 0)
    {
        /*
         * The value we just tried writing ended up being empty. Move the cursor back to the end of
         * the key and denote that it has an empty value.
         */
        const uint32_t key_len = strlen(key_name);
        cursor = key_len;
        written = snprintf(&buf[cursor], max_str_len - cursor, " (empty)");
    }
    if (written < 0 || (cursor + written) > max_str_len)
    {
        return -1;
    }
    cursor += written;

    embeddedCliPrint(cli, buf);

    return 0;
}

int mmagic_cli_iperf_get_server(struct mmagic_data *core, EmbeddedCli *cli)
{
    struct mmagic_iperf_data *data = mmagic_data_get_iperf(core);
    const char *key_name = "iperf.server";
    MM_STATIC_ASSERT((sizeof("iperf.server") - 1) < KEY_NAME_PADDING,
                     "Key must be shorter than padding");

    char buf[MMAGIC_CLI_PRINT_BUF_LEN] = { 0 };
    /* -1 to allow for a NULL terminator at the end */
    const size_t max_str_len = sizeof(buf) - 1;
    size_t cursor = 0;
    int written = 0;

    written = snprintf(&buf[cursor], max_str_len - cursor, "%-*s", KEY_NAME_PADDING, key_name);
    if (written < 0 || (cursor + written) > max_str_len)
    {
        return -1;
    }
    cursor += written;
    written =
        mmagic_struct_ip_addr_to_string(&data->config.server, &buf[cursor], max_str_len - cursor);
    if (written == 0)
    {
        /*
         * The value we just tried writing ended up being empty. Move the cursor back to the end of
         * the key and denote that it has an empty value.
         */
        const uint32_t key_len = strlen(key_name);
        cursor = key_len;
        written = snprintf(&buf[cursor], max_str_len - cursor, " (empty)");
    }
    if (written < 0 || (cursor + written) > max_str_len)
    {
        return -1;
    }
    cursor += written;

    embeddedCliPrint(cli, buf);

    return 0;
}

int mmagic_cli_iperf_get_port(struct mmagic_data *core, EmbeddedCli *cli)
{
    struct mmagic_iperf_data *data = mmagic_data_get_iperf(core);
    const char *key_name = "iperf.port";
    MM_STATIC_ASSERT((sizeof("iperf.port") - 1) < KEY_NAME_PADDING,
                     "Key must be shorter than padding");

    char buf[MMAGIC_CLI_PRINT_BUF_LEN] = { 0 };
    /* -1 to allow for a NULL terminator at the end */
    const size_t max_str_len = sizeof(buf) - 1;
    size_t cursor = 0;
    int written = 0;

    written = snprintf(&buf[cursor], max_str_len - cursor, "%-*s", KEY_NAME_PADDING, key_name);
    if (written < 0 || (cursor + written) > max_str_len)
    {
        return -1;
    }
    cursor += written;
    written = mmagic_uint16_t_to_string(data->config.port, &buf[cursor], max_str_len - cursor);
    if (written == 0)
    {
        /*
         * The value we just tried writing ended up being empty. Move the cursor back to the end of
         * the key and denote that it has an empty value.
         */
        const uint32_t key_len = strlen(key_name);
        cursor = key_len;
        written = snprintf(&buf[cursor], max_str_len - cursor, " (empty)");
    }
    if (written < 0 || (cursor + written) > max_str_len)
    {
        return -1;
    }
    cursor += written;

    embeddedCliPrint(cli, buf);

    return 0;
}

int mmagic_cli_iperf_get_amount(struct mmagic_data *core, EmbeddedCli *cli)
{
    struct mmagic_iperf_data *data = mmagic_data_get_iperf(core);
    const char *key_name = "iperf.amount";
    MM_STATIC_ASSERT((sizeof("iperf.amount") - 1) < KEY_NAME_PADDING,
                     "Key must be shorter than padding");

    char buf[MMAGIC_CLI_PRINT_BUF_LEN] = { 0 };
    /* -1 to allow for a NULL terminator at the end */
    const size_t max_str_len = sizeof(buf) - 1;
    size_t cursor = 0;
    int written = 0;

    written = snprintf(&buf[cursor], max_str_len - cursor, "%-*s", KEY_NAME_PADDING, key_name);
    if (written < 0 || (cursor + written) > max_str_len)
    {
        return -1;
    }
    cursor += written;
    written = mmagic_int32_t_to_string(data->config.amount, &buf[cursor], max_str_len - cursor);
    if (written == 0)
    {
        /*
         * The value we just tried writing ended up being empty. Move the cursor back to the end of
         * the key and denote that it has an empty value.
         */
        const uint32_t key_len = strlen(key_name);
        cursor = key_len;
        written = snprintf(&buf[cursor], max_str_len - cursor, " (empty)");
    }
    if (written < 0 || (cursor + written) > max_str_len)
    {
        return -1;
    }
    cursor += written;

    embeddedCliPrint(cli, buf);

    return 0;
}

/********* Setters **********/

int mmagic_cli_iperf_set_mode(struct mmagic_data *core, EmbeddedCli *cli, const char *val)
{
    struct mmagic_iperf_data *data = mmagic_data_get_iperf(core);

    if (mmagic_string_to_enum_iperf_mode(&data->config.mode, val))
    {
        return -1;
    }

    mmagic_cli_iperf_get_mode(core, cli);

    return 0;
}

int mmagic_cli_iperf_set_server(struct mmagic_data *core, EmbeddedCli *cli, const char *val)
{
    struct mmagic_iperf_data *data = mmagic_data_get_iperf(core);

    if (mmagic_string_to_struct_ip_addr(&data->config.server, val))
    {
        return -1;
    }

    mmagic_cli_iperf_get_server(core, cli);

    return 0;
}

int mmagic_cli_iperf_set_port(struct mmagic_data *core, EmbeddedCli *cli, const char *val)
{
    struct mmagic_iperf_data *data = mmagic_data_get_iperf(core);

    if (mmagic_string_to_uint16_t(&data->config.port, val))
    {
        return -1;
    }

    mmagic_cli_iperf_get_port(core, cli);

    return 0;
}

int mmagic_cli_iperf_set_amount(struct mmagic_data *core, EmbeddedCli *cli, const char *val)
{
    struct mmagic_iperf_data *data = mmagic_data_get_iperf(core);

    if (mmagic_string_to_int32_t(&data->config.amount, val))
    {
        return -1;
    }

    mmagic_cli_iperf_get_amount(core, cli);

    return 0;
}

/********* Dictionary **********
 *
 * This list must be in alphabetical order as @c mmagic_cli_element_search() is implemented using
 * a binary search which requires an ordered list.
 */
struct mmagic_cli_config_elem iperf_cli_config_vars[] = {
    { "amount", mmagic_cli_iperf_get_amount, mmagic_cli_iperf_set_amount },
    { "mode", mmagic_cli_iperf_get_mode, mmagic_cli_iperf_set_mode },
    { "port", mmagic_cli_iperf_get_port, mmagic_cli_iperf_set_port },
    { "server", mmagic_cli_iperf_get_server, mmagic_cli_iperf_set_server },
};

/********* IPERF Configuration Getter/Setter Handlers **********/
void mmagic_cli_iperf_get(struct mmagic_cli *ctx, EmbeddedCli *cli, const char *config_var)
{
    struct mmagic_data *core = &ctx->core;

    if (config_var == NULL)
    {
        embeddedCliPrint(cli, "Invalid argument");
        return;
    }

    uint32_t num_elements = sizeof(iperf_cli_config_vars) / sizeof(iperf_cli_config_vars[0]);

    if (!strcmp("all", config_var))
    {
        for (; num_elements > 0; num_elements--)
        {
            iperf_cli_config_vars[num_elements - 1].get(core, cli);
        }
        return;
    }

    struct mmagic_cli_config_elem *elem =
        mmagic_cli_element_search(iperf_cli_config_vars, num_elements, config_var);
    if (elem == NULL)
    {
        mmagic_cli_printf(cli, "Unable to find config variable 'iperf.%s'", config_var);
        return;
    }

    if (elem->get == NULL)
    {
        embeddedCliPrint(cli, "Unable to find getter");
        return;
    }

    if (elem->get(core, cli))
    {
        embeddedCliPrint(cli, "Get function failed");
    }
}

void mmagic_cli_iperf_set(struct mmagic_cli *ctx,
                          EmbeddedCli *cli,
                          const char *config_var,
                          const char *val)
{
    struct mmagic_data *core = &ctx->core;

    uint32_t num_elements = sizeof(iperf_cli_config_vars) / sizeof(iperf_cli_config_vars[0]);

    struct mmagic_cli_config_elem *elem =
        mmagic_cli_element_search(iperf_cli_config_vars, num_elements, config_var);
    if (elem == NULL)
    {
        mmagic_cli_printf(cli, "Unable to find config variable 'iperf.%s'", config_var);
        return;
    }

    if (elem->set == NULL)
    {
        embeddedCliPrint(cli, "Unable to find setter");
        return;
    }

    if (elem->set(core, cli, val))
    {
        mmagic_cli_printf(cli, "Set iperf.%s failed", elem->name);
    }
}

/********* Persistence *******/
void mmagic_cli_iperf_commit(struct mmagic_cli *ctx, EmbeddedCli *cli, const char *config_var)
{
    if ((config_var != NULL) && strcmp("all", config_var))
    {
        embeddedCliPrint(cli, "Unexpected argument! Only \'iperf\' or \'iperf.all\' supported.");
        return;
    }

    mmagic_core_iperf_save_all(&ctx->core);
    embeddedCliPrint(cli, "Successfully committed 'iperf' variables");
}

void mmagic_cli_iperf_load(struct mmagic_cli *ctx, EmbeddedCli *cli)
{
    MM_UNUSED(cli);
    mmagic_core_iperf_load_all(&ctx->core);
}

/********* CLI Command Handlers **********/

void mmagic_cli_iperf_run(EmbeddedCli *cli, char *args, void *context);

/********* Register bindings function definition **********/
void mmagic_cli_iperf_register_bindings(EmbeddedCli *cli, struct mmagic_data *core)
{
    embeddedCliAddBinding(
        cli,
        (CliCommandBinding){
            "iperf-run",
            "Starts an iperf session using the current values in the the subsystem config.",
            true,
            core,
            mmagic_cli_iperf_run });
}

void mmagic_cli_iperf_init(struct mmagic_cli *ctx)
{
    /* Register Commands */
    mmagic_cli_iperf_register_bindings(ctx->cli, &ctx->core);

    /* Register config variable accessor functions */
    struct mmagic_cli_config_accessor *accessor =
        (struct mmagic_cli_config_accessor *)mmosal_malloc(sizeof(*accessor));
    MMOSAL_ASSERT(accessor);

    mmosal_safer_strcpy(accessor->name, "iperf", sizeof(accessor->name));
    accessor->get = mmagic_cli_iperf_get;
    accessor->set = mmagic_cli_iperf_set;
    accessor->commit = mmagic_cli_iperf_commit;
    accessor->next = NULL;

    mmagic_cli_register_config_accessor(ctx, accessor);
}
