/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#pragma once

#include "core/autogen/mmagic_core_data.h"
#include "core/autogen/mmagic_core_types.h"
#include "cli/embedded_cli.h"
#include "cli/mmagic_cli.h"

/**
 * Register the sys command bindings with the cli.
 *
 * @param cli Reference to the CLI instance.
 * @param mmagicd Reference to the mmagic_core data structure.
 */
void mmagic_cli_sys_register_bindings(EmbeddedCli *cli, struct mmagic_data *mmagicd);

/**
 * Retrieve the value of the specified variable and display on the CLI.
 *
 * @param ctx       Reference to the global mmagic data structure.
 * @param cli       Reference to the CLI instance.
 * @param config_var Reference to a @c NULL terminated string containing the config variable to
 *                  display the value for. @c "all" for all of the available config
 */
void mmagic_cli_sys_get(struct mmagic_cli *ctx, EmbeddedCli *cli, const char *config_var);

/**
 * Set the value of the specified variable and display the new value on the CLI.
 *
 * @param ctx       Reference to the global mmagic data structure.
 * @param cli       Reference to the CLI instance.
 * @param config_var Reference to a @c NULL terminated string containing the config variable to
 *                  set the value for.
 * @param val       Reference to a @c NULL terminated string containing the value.
 */
void mmagic_cli_sys_set(struct mmagic_cli *ctx,
                        EmbeddedCli *cli,
                        const char *config_var,
                        const char *val);

/**
 * Commit the value of the specified variable to persistent storage.
 *
 * @param ctx       Reference to the global mmagic data structure.
 * @param cli       Reference to the CLI instance.
 * @param config_var Reference to a @c NULL terminated string containing the config variable to
 *                  save. @c "all" for all of the available config
 */
void mmagic_cli_sys_commit(struct mmagic_cli *ctx, EmbeddedCli *cli, const char *config_var);

/**
 * Loads all stored variables of the module from persistent storage.
 *
 * @param ctx       Reference to the global mmagic data structure.
 * @param cli       Reference to the CLI instance.
 */
void mmagic_cli_sys_load(struct mmagic_cli *ctx, EmbeddedCli *cli);

/**
 * Initializes the CLI sys module.
 *
 * @param ctx       Reference to the global mmagic data structure.
 */
void mmagic_cli_sys_init(struct mmagic_cli *ctx);
