/*
 * GENERATED by gen_stubs.py -- do not edit by hand.
 *
 * Stubs for the radio stack below the mesh cut line: the chip driver's
 * upper half, STA-mode connection and scan, rate control, block-ack, TWT and
 * the hostap supplicant. The simulator links the real mesh, datapath, packet,
 * key and crypto code; these are what it deliberately does not.
 *
 * Signatures are scraped from the real headers, so a change there breaks the
 * build here rather than silently producing a stub that no longer matches.
 * Each stub counts its calls: simnode_stub_hits() lets a test assert that a
 * path it believes is mesh-only never fell through into the radio stack.
 */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* The real headers, so every stub's types are the firmware's own. */
#include "mmpkt.h"
#include "mmwlan.h"
#include "mmdrv.h"
#include "umac/umac.h"
#include "umac/data/umac_data.h"
#include "umac/datapath/umac_datapath.h"
#include "umac/interface/umac_interface.h"
#include "umac/connection/umac_connection.h"
#include "umac/config/umac_config.h"
#include "umac/core/umac_core.h"
#include "umac/ba/umac_ba.h"
#include "umac/rc/umac_rc.h"
#include "umac/twt/umac_twt.h"
#include "umac/stats/umac_stats.h"
#include "umac/supplicant_shim/umac_supp_shim.h"
#include "dot11/dot11.h"
#include "dot11/dot11_ies.h"

static unsigned s_hits[53];
static const char *const s_names[53] = {
    "bip_is_valid",
    "ie_aid_request_build",
    "ie_morse_info_build",
    "ie_twt_build",
    "ie_wmm_info_build",
    "ieee80211_crc32",
    "umac_ba_get_expected_rx_seq_num",
    "umac_ba_get_reorder_buffer_size",
    "umac_ba_is_ampdu_permitted",
    "umac_ba_process_rx_frame",
    "umac_ba_session_init",
    "umac_ba_set_expected_rx_seq_num",
    "umac_config_get_default_qos_queue_params",
    "umac_config_get_listen_interval",
    "umac_config_get_rts_threshold",
    "umac_config_get_supported_channel_width_field_override",
    "umac_config_is_ampdu_enabled",
    "umac_config_is_non_tim_mode_enabled",
    "umac_config_is_opclass_check_enabled",
    "umac_config_rc_is_sgi_enabled",
    "umac_connection_addr_matches_bssid",
    "umac_connection_check_signal_change",
    "umac_connection_get_stad",
    "umac_connection_get_state",
    "umac_connection_handle_ack_status",
    "umac_connection_populate_tx_metadata",
    "umac_connection_process_assoc_reassoc_rsp",
    "umac_connection_process_auth_resp",
    "umac_connection_process_beacon_ies",
    "umac_connection_process_deauth_rx",
    "umac_connection_process_disassoc_req",
    "umac_core_cancel_timeout",
    "umac_core_evt_wake",
    "umac_interface_get_current_s1g_operation_info",
    "umac_interface_get_rx_pkt_ext_cb",
    "umac_interface_register_rx_pkt_ext_cb",
    "umac_interface_set_channel_from_regdb",
    "umac_mesh_ccmp_kat_run",
    "umac_rc_feedback",
    "umac_rc_init_rate_table_data",
    "umac_rc_init_rate_table_mgmt",
    "umac_rc_start",
    "umac_rc_stop",
    "umac_scan_process_probe_resp",
    "umac_supp_add_mesh_interface",
    "umac_supp_l2_sock_receive",
    "umac_supp_mesh_new_peer",
    "umac_supp_notify_signal_change",
    "umac_supp_process_mgmt_frame",
    "umac_supp_process_unprotected_deauth",
    "umac_supp_process_unprotected_disassoc",
    "umac_supp_tx_status",
    "umac_twt_get_config",
};

static uint8_t s_new_peer_addr[6];
static uint8_t s_new_peer_ies[256];
static size_t s_new_peer_len;

unsigned simnode_stub_hits(const char *name)
{
    for (unsigned i = 0; i < 53; i++)
    {
        if (strcmp(s_names[i], name) == 0) { return s_hits[i]; }
    }
    return 0u;
}

void simnode_stub_reset(void)
{
    memset(s_hits, 0, sizeof(s_hits));
}

/* umac_supp_shim.h */
bool bip_is_valid(struct umac_sta_data *stad, const struct dot11_hdr *header, const uint8_t *data, size_t data_len)
{
    s_hits[0]++;
    return false;
}

/* aid_request.h */
void ie_aid_request_build(struct consbuf *buf)
{
    s_hits[1]++;
    return;
}

/* morse_ie.h */
void ie_morse_info_build(struct umac_data *umacd, struct consbuf *buf)
{
    s_hits[2]++;
    return;
}

/* twt_ie.h */
void ie_twt_build(struct umac_data *umacd, struct consbuf *buf)
{
    s_hits[3]++;
    return;
}

/* wmm.h */
void ie_wmm_info_build(struct consbuf *buf)
{
    s_hits[4]++;
    return;
}

/* crc32.h */
u32 ieee80211_crc32(const u8 *frame, size_t frame_len)
{
    s_hits[5]++;
    return 0;
}

/* umac_ba.h */
int32_t umac_ba_get_expected_rx_seq_num(struct umac_sta_data *stad, uint8_t tid)
{
    s_hits[6]++;
    return 0;
}

/* umac_ba.h */
uint8_t umac_ba_get_reorder_buffer_size(struct umac_sta_data *stad, uint8_t tid)
{
    s_hits[7]++;
    return 0;
}

/* umac_ba.h */
bool umac_ba_is_ampdu_permitted(struct umac_sta_data *stad, uint8_t tid)
{
    s_hits[8]++;
    return false;
}

/* umac_ba.h */
void umac_ba_process_rx_frame(struct umac_sta_data *stad, const uint8_t *frame, uint32_t frame_len)
{
    s_hits[9]++;
    return;
}

/* umac_ba.h */
void umac_ba_session_init(struct umac_sta_data *stad, uint8_t tid, uint16_t ssc, uint16_t timeout)
{
    s_hits[10]++;
    return;
}

/* umac_ba.h */
void umac_ba_set_expected_rx_seq_num(struct umac_sta_data *stad, uint8_t tid, uint16_t seq_num)
{
    s_hits[11]++;
    return;
}

/* umac_config.h */
const struct mmwlan_qos_queue_params * umac_config_get_default_qos_queue_params(struct umac_data *umacd)
{
    s_hits[12]++;
    return NULL;
}

/* umac_config.h */
uint16_t umac_config_get_listen_interval(struct umac_data *umacd)
{
    s_hits[13]++;
    return 0;
}

/* umac_config.h */
uint32_t umac_config_get_rts_threshold(struct umac_data *umacd)
{
    s_hits[14]++;
    return 0;
}

/* umac_config.h */
int umac_config_get_supported_channel_width_field_override(struct umac_data *umacd)
{
    s_hits[15]++;
    return 0;
}

/* umac_config.h */
bool umac_config_is_ampdu_enabled(struct umac_data *umacd)
{
    s_hits[16]++;
    return false;
}

/* umac_config.h */
bool umac_config_is_non_tim_mode_enabled(struct umac_data *umacd)
{
    s_hits[17]++;
    return false;
}

/* umac_config.h */
bool umac_config_is_opclass_check_enabled(struct umac_data *umacd)
{
    s_hits[18]++;
    return false;
}

/* umac_config.h */
bool umac_config_rc_is_sgi_enabled(struct umac_data *umacd)
{
    s_hits[19]++;
    return false;
}

/* umac_connection.h */
bool umac_connection_addr_matches_bssid(struct umac_data *umacd, const uint8_t *addr)
{
    s_hits[20]++;
    return false;
}

/* umac_connection.h */
enum umac_connection_signal_change umac_connection_check_signal_change(struct umac_data *umacd, int16_t rssi)
{
    s_hits[21]++;
    return (enum umac_connection_signal_change)0;
}

/* umac_connection.h */
struct umac_sta_data * umac_connection_get_stad(struct umac_data *umacd)
{
    s_hits[22]++;
    return NULL;
}

/* umac_connection.h */
enum mmwlan_sta_state umac_connection_get_state(struct umac_data *umacd)
{
    s_hits[23]++;
    return (enum mmwlan_sta_state)0;
}

/* umac_connection.h */
void umac_connection_handle_ack_status(struct mmpkt *mmpkt, struct umac_data *umacd, bool acked)
{
    s_hits[24]++;
    return;
}

/* umac_connection.h */
void umac_connection_populate_tx_metadata(struct umac_data *umacd, struct mmdrv_tx_metadata *tx_metadata)
{
    s_hits[25]++;
    return;
}

/* umac_connection.h */
void umac_connection_process_assoc_reassoc_rsp(struct umac_data *umacd, struct mmpktview *rxbufview)
{
    s_hits[26]++;
    return;
}

/* umac_connection.h */
void umac_connection_process_auth_resp(struct umac_data *umacd, struct mmpktview *rxbufview)
{
    s_hits[27]++;
    return;
}

/* umac_connection.h */
void umac_connection_process_beacon_ies(struct umac_data *umacd, const uint8_t *ies, uint32_t ies_len)
{
    s_hits[28]++;
    return;
}

/* umac_connection.h */
void umac_connection_process_deauth_rx(struct umac_data *umacd, struct mmpktview *rxbufview)
{
    s_hits[29]++;
    return;
}

/* umac_connection.h */
void umac_connection_process_disassoc_req(struct umac_data *umacd, struct mmpktview *rxbufview)
{
    s_hits[30]++;
    return;
}

/* umac_core.h */
int umac_core_cancel_timeout(struct umac_data *umacd, umac_core_timeout_handler_t handler, void *arg1, void *arg2)
{
    s_hits[31]++;
    return 0;
}

/* umac_core.h */
void umac_core_evt_wake(struct umac_data *umacd)
{
    s_hits[32]++;
    return;
}

/* umac_interface.h */
const struct ie_s1g_operation * umac_interface_get_current_s1g_operation_info(struct umac_data *umacd)
{
    s_hits[33]++;
    return NULL;
}

/* umac_interface.h */
mmwlan_rx_pkt_ext_cb_t umac_interface_get_rx_pkt_ext_cb(struct umac_data *umacd, enum mmwlan_vif vif, void **arg)
{
    s_hits[34]++;
    return 0;
}

/* umac_interface.h */
enum mmwlan_status umac_interface_register_rx_pkt_ext_cb(struct umac_data *umacd, enum mmwlan_vif vif, mmwlan_rx_pkt_ext_cb_t callback, void *arg)
{
    s_hits[35]++;
    return (enum mmwlan_status)0;
}

/* umac_interface.h */
enum mmwlan_status umac_interface_set_channel_from_regdb(struct umac_data *umacd, const struct mmwlan_s1g_channel *channel, bool is_off_channel)
{
    s_hits[36]++;
    return (enum mmwlan_status)0;
}

/* umac_mesh_ccmp_kat.h */
void umac_mesh_ccmp_kat_run(void)
{
    s_hits[37]++;
    return;
}

/* umac_rc.h */
void umac_rc_feedback(struct umac_sta_data *stad, struct mmdrv_tx_metadata *tx_metadata)
{
    s_hits[38]++;
    return;
}

/* umac_rc.h */
void umac_rc_init_rate_table_data(struct umac_sta_data *stad, struct mmrc_rate_table *table, bool rts_required, uint32_t frame_size)
{
    s_hits[39]++;
    return;
}

/* umac_rc.h */
void umac_rc_init_rate_table_mgmt(struct umac_data *umacd, struct mmrc_rate_table *table, bool rts_required)
{
    s_hits[40]++;
    return;
}

/* umac_rc.h */
void umac_rc_start(struct umac_sta_data *stad, uint8_t sgi_flags, uint8_t max_mcs)
{
    s_hits[41]++;
    return;
}

/* umac_rc.h */
void umac_rc_stop(struct umac_sta_data *stad)
{
    s_hits[42]++;
    return;
}

/* umac_scan.h */
void umac_scan_process_probe_resp(struct umac_data *umacd, struct mmpktview *rxbufview)
{
    s_hits[43]++;
    return;
}

/* umac_supp_shim.h */
enum mmwlan_status umac_supp_add_mesh_interface(struct umac_data *umacd)
{
    s_hits[44]++;
    return (enum mmwlan_status)0;
}

/* umac_supp_shim.h */
void umac_supp_l2_sock_receive(struct umac_data *umacd, const uint8_t *payload, size_t payload_len, const uint8_t *src_addr)
{
    s_hits[45]++;
    return;
}

/* umac_supp_shim.h */
void umac_supp_mesh_new_peer(const uint8_t *addr, const uint8_t *ies, size_t ies_len)
{
    s_hits[46]++;
    if (addr != NULL) { memcpy(s_new_peer_addr, addr, sizeof(s_new_peer_addr)); }
    s_new_peer_len = (ies != NULL && ies_len <= sizeof(s_new_peer_ies)) ? ies_len : 0u;
    if (s_new_peer_len != 0u) { memcpy(s_new_peer_ies, ies, s_new_peer_len); }
    return;
}

/* umac_supp_shim.h */
void umac_supp_notify_signal_change(struct umac_data *umacd, int16_t rssi, bool above_threshold)
{
    s_hits[47]++;
    return;
}

/* umac_supp_shim.h */
void umac_supp_process_mgmt_frame(struct umac_data *umacd, struct mmpktview *rxbufview)
{
    s_hits[48]++;
    return;
}

/* umac_supp_shim.h */
void umac_supp_process_unprotected_deauth(struct umac_data *umacd, uint16_t reason_code, const uint8_t *sa, const uint8_t *da)
{
    s_hits[49]++;
    return;
}

/* umac_supp_shim.h */
void umac_supp_process_unprotected_disassoc(struct umac_data *umacd, uint16_t reason_code, const uint8_t *sa, const uint8_t *da)
{
    s_hits[50]++;
    return;
}

/* umac_supp_shim.h */
void umac_supp_tx_status(struct umac_data *umacd, struct mmpkt *pkt, bool acked)
{
    s_hits[51]++;
    return;
}

/* umac_twt.h */
const struct mmwlan_twt_config_args * umac_twt_get_config(struct umac_data *umacd)
{
    s_hits[52]++;
    return NULL;
}

/* The last candidate offered to umac_supp_mesh_new_peer: its address and IEs. */
size_t simnode_last_new_peer(uint8_t addr[6], const uint8_t **ies)
{
    if (addr != NULL) { memcpy(addr, s_new_peer_addr, sizeof(s_new_peer_addr)); }
    if (ies != NULL) { *ies = s_new_peer_ies; }
    return s_new_peer_len;
}
