#!/usr/bin/env python3
"""Generate fake_radio_stack.c: stubs for everything below the mesh cut line.

The simulator links the REAL mesh, datapath, packet, key and crypto code. What
it cannot link is the radio stack (chip driver, STA-mode connection, scan,
rate control, block-ack, TWT), the RTOS, and the hostap supplicant. Those get
stubs -- and the stubs are GENERATED from the real declarations rather than
written by hand, because a stub whose signature has drifted from the header is
a silent lie: it links, it runs, and it tests nothing.

Every stub counts its own calls, so a test can assert that a path it believes
is mesh-only never dropped into the radio stack.

Usage: gen_stubs.py <undefined-symbol-list> <include-dir>...
"""
import re
import subprocess
import sys

# Hand-written elsewhere: the RTOS (fake_rtos.c) and the chip (fake_chip.c).
HAND_WRITTEN = re.compile(r'^(mmosal_|mmdrv_|mmhal_|umac_config_get_channel_list$|umac_interface_(get_capabilities|max_supported_bw|get_control_response_bw_1mhz_out_enabled|get_vif_id|get_mac_addr|addr_matches_mac_addr)$|mmwlan_get_vif_mac_addr$|umac_connection_get_sta_args$|umac_interface_add$)')

# Stubs that also keep their last call's arguments, so a test can assert on
# what the firmware handed the supplicant, not only that it called it. The
# snippet runs after the hit count; RECORD_API is emitted once, after the stubs.
RECORD = {
    'umac_supp_mesh_new_peer':
        '    if (addr != NULL) { memcpy(s_new_peer_addr, addr, sizeof(s_new_peer_addr)); }\n'
        '    s_new_peer_len = (ies != NULL && ies_len <= sizeof(s_new_peer_ies)) ? ies_len : 0u;\n'
        '    if (s_new_peer_len != 0u) { memcpy(s_new_peer_ies, ies, s_new_peer_len); }\n',
}
RECORD_STATE = '''static uint8_t s_new_peer_addr[6];
static uint8_t s_new_peer_ies[256];
static size_t s_new_peer_len;

'''
RECORD_API = '''
/* The last candidate offered to umac_supp_mesh_new_peer: its address and IEs. */
size_t simnode_last_new_peer(uint8_t addr[6], const uint8_t **ies)
{
    if (addr != NULL) { memcpy(addr, s_new_peer_addr, sizeof(s_new_peer_addr)); }
    if (ies != NULL) { *ies = s_new_peer_ies; }
    return s_new_peer_len;
}
'''

HEADER = '''/*
 * GENERATED by gen_stubs.py -- do not edit by hand.
 *
 * Stubs for the radio stack below the mesh cut line: the chip driver's
 * upper half, STA-mode connection and scan, rate control, block-ack, TWT and
 * the hostap supplicant. The simulator links the real mesh, datapath, packet,
 * key and crypto code; these are what it deliberately does not.
 *
 * Signatures are scraped from the real headers, so a change there breaks the
 * build here rather than silently producing a stub that no longer matches.
 * Each stub counts its calls: simnode_stub_hits() lets a test assert that a
 * path it believes is mesh-only never fell through into the radio stack.
 */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* The real headers, so every stub's types are the firmware's own. */
#include "mmpkt.h"
#include "mmwlan.h"
#include "mmdrv.h"
#include "umac/umac.h"
#include "umac/data/umac_data.h"
#include "umac/datapath/umac_datapath.h"
#include "umac/interface/umac_interface.h"
#include "umac/connection/umac_connection.h"
#include "umac/config/umac_config.h"
#include "umac/core/umac_core.h"
#include "umac/ba/umac_ba.h"
#include "umac/rc/umac_rc.h"
#include "umac/twt/umac_twt.h"
#include "umac/stats/umac_stats.h"
#include "umac/supplicant_shim/umac_supp_shim.h"
#include "dot11/dot11.h"
#include "dot11/dot11_ies.h"

'''


def decl_for(sym, incdirs, roots):
    """Find the real declaration of sym, preferring a header."""
    pat = re.compile(r'(^|[^A-Za-z0-9_])' + re.escape(sym) + r'\s*\(')
    for root in roots:
        try:
            out = subprocess.run(['grep', '-rn', '--include=*.h', '-E',
                                  r'\b' + sym + r'\s*\(', root],
                                 capture_output=True, text=True, timeout=60).stdout
        except Exception:
            continue
        for line in out.splitlines():
            try:
                path, lineno, _ = line.split(':', 2)
            except ValueError:
                continue
            try:
                text = open(path, errors='replace').read()
            except OSError:
                continue
            # Doc comments sit directly above declarations; left in, they get
            # glued onto the return type and every stub comes out malformed.
            text = re.sub(r'/\*.*?\*/', ' ', text, flags=re.S)
            text = re.sub(r'//[^\n]*', ' ', text)
            text = re.sub(r'^\s*#.*$', ' ', text, flags=re.M)
            # Join the statement containing the match.
            idx = text.find(sym)
            while idx != -1:
                before = text.rfind(';', 0, idx)
                brace = text.rfind('}', 0, idx)
                start = max(before, brace) + 1
                end = text.find(';', idx)
                if end == -1:
                    break
                stmt = ' '.join(text[start:end].split())
                if pat.search(stmt) and '(' in stmt and not stmt.startswith('#'):
                    if re.match(r'^(typedef|return|if|while|for)\b', stmt):
                        idx = text.find(sym, idx + 1)
                        continue
                    return stmt, path
                idx = text.find(sym, idx + 1)
    return None, None


def body_for(ret):
    r = ret.strip()
    if r == 'void':
        return '    return;'
    if '*' in r:
        return '    return NULL;'
    if r in ('bool',):
        return '    return false;'
    if r.startswith('enum '):
        return '    return (%s)0;' % r
    if r.startswith('struct ') or r.startswith('union '):
        return '    %s zero; memset(&zero, 0, sizeof(zero)); return zero;' % r
    return '    return 0;'


def main():
    syms = [s.strip() for s in open(sys.argv[1]) if s.strip()]
    roots = sys.argv[2:]
    out, names, unresolved = [], [], []
    for sym in syms:
        if HAND_WRITTEN.match(sym):
            continue
        stmt, path = decl_for(sym, None, roots)
        if not stmt:
            unresolved.append(sym)
            continue
        # Split "ret name(args)" on the symbol's own paren.
        m = re.search(r'(.*?)\b' + re.escape(sym) + r'\s*\((.*)\)\s*$', stmt)
        if not m:
            unresolved.append(sym)
            continue
        ret = m.group(1).replace('extern', '').replace('static', '').strip()
        # A plausible return type is one or two words plus stars, nothing else.
        if not re.match(r'^(const\s+|unsigned\s+|signed\s+|struct\s+|union\s+|enum\s+)*[A-Za-z_][A-Za-z0-9_]*(\s*\*)*$', ret):
            unresolved.append(sym)
            continue
        args = m.group(2).strip() or 'void'
        if not ret:
            unresolved.append(sym)
            continue
        idx = len(names)
        names.append(sym)
        out.append('/* %s */\n%s %s(%s)\n{\n    s_hits[%d]++;\n%s%s\n}\n'
                   % (path.split('/')[-1], ret, sym, args, idx, RECORD.get(sym, ''),
                      body_for(ret)))

    body = HEADER
    body += 'static unsigned s_hits[%d];\n' % max(len(names), 1)
    body += 'static const char *const s_names[%d] = {\n' % max(len(names), 1)
    body += ''.join('    "%s",\n' % n for n in names) or '    "",\n'
    body += '};\n\n'
    body += RECORD_STATE
    body += ('unsigned simnode_stub_hits(const char *name)\n{\n'
             '    for (unsigned i = 0; i < %d; i++)\n'
             '    {\n        if (strcmp(s_names[i], name) == 0) { return s_hits[i]; }\n    }\n'
             '    return 0u;\n}\n\n'
             'void simnode_stub_reset(void)\n{\n    memset(s_hits, 0, sizeof(s_hits));\n}\n\n'
             % max(len(names), 1))
    body += '\n'.join(out)
    body += RECORD_API
    open('fake_radio_stack.c', 'w').write(body)
    sys.stderr.write('fake_radio_stack.c: %d stubs\n' % len(names))
    if unresolved:
        sys.stderr.write('UNRESOLVED (%d): %s\n' % (len(unresolved), ' '.join(unresolved)))


if __name__ == '__main__':
    main()
