#!/usr/bin/env python3
"""Regenerate warthog_globals.c from main/at.c.

The g_warthog_* counters and gates are DEFINED app-side in main/at.c: morselib
is a static archive, so a definition inside it would never be extracted to
satisfy a reference from main/. The host harness links morselib's objects
without main/, so it must supply that same storage -- with at.c's exact types
and initial values, or a test reads a counter the firmware would have read
differently.

Scraping at.c is the only form that stays true as at.c changes; a hand-copied
list goes stale silently, and in a test harness that reads as a pass.

Usage: gen_warthog_globals.py <path-to-at.c>   (writes warthog_globals.c; reads cfg.h beside it
for the build defaults at.c's initialisers name)
"""
import os
import re
import sys

HEADER = '''/*
 * GENERATED by gen_warthog_globals.py from main/at.c -- do not edit by hand.
 *
 * Mirrors at.c's definitions of every g_warthog_* object, with at.c's own
 * types and initial values. See the generator for why this is scraped rather
 * than written out by hand.
 */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* ESP-IDF puts a couple of these in RTC memory that survives deep sleep. The
 * host has no such thing and ordinary .bss is the truthful stand-in. */
#define RTC_NOINIT_ATTR

'''


def statements(text):
    """File-scope statements, brace- and string-aware, one per yield."""
    depth = 0
    buf = []
    i = 0
    n = len(text)
    while i < n:
        c = text[i]
        if c == '"' or c == "'":
            q = c
            buf.append(c)
            i += 1
            while i < n:
                buf.append(text[i])
                if text[i] == '\\':
                    i += 2
                    if i - 1 < n:
                        buf.append(text[i - 1])
                    continue
                if text[i] == q:
                    i += 1
                    break
                i += 1
            continue
        if c == '{':
            # A brace after '=' is an initialiser, not a body: keep it.
            if depth == 0 and '=' in ''.join(buf):
                init = 0
                while i < n:
                    buf.append(text[i])
                    if text[i] == '{':
                        init += 1
                    elif text[i] == '}':
                        init -= 1
                        if init == 0:
                            i += 1
                            break
                    i += 1
                continue
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                buf = []      # a function body just ended; drop its signature
                i += 1
                continue
        elif c == ';' and depth == 0:
            yield ''.join(buf).strip()
            buf = []
            i += 1
            continue
        buf.append(c)
        i += 1


def cfg_macros(path, names):
    """cfg.h's definitions of @p names verbatim: a lone #define, or a whole #if block of #defines."""
    lines = open(path).read().split('\n')
    out, i = [], 0
    while i < len(lines):
        if re.match(r'\s*#\s*if', lines[i]):
            depth, j = 0, i
            while j < len(lines):
                depth += 1 if re.match(r'\s*#\s*if', lines[j]) else 0
                depth -= 1 if re.match(r'\s*#\s*endif', lines[j]) else 0
                j += 1
                if depth == 0:
                    break
            block = lines[i:j]
            defs = set(re.findall(r'#\s*define\s+(WARTHOG_[A-Z0-9_]+)', '\n'.join(block)))
            if defs and defs <= names and all(re.match(r'\s*#', b) for b in block):
                out.append('\n'.join(b.strip() for b in block))
            i = j
            continue
        m = re.match(r'\s*#\s*define\s+(WARTHOG_[A-Z0-9_]+)\s', lines[i])
        if m and m.group(1) in names:
            out.append(lines[i].strip())
        i += 1
    missing = names - set(re.findall(r'#\s*define\s+(WARTHOG_[A-Z0-9_]+)', '\n'.join(out)))
    if missing:
        sys.exit('initialisers use %s, defined in neither at.c nor cfg.h' % ', '.join(sorted(missing)))
    return out


def main():
    at = sys.argv[1] if len(sys.argv) > 1 else '../../../../main/at.c'
    src = open(at).read()
    # Comments carry no storage and their contents confuse the scan.
    src = re.sub(r'/\*.*?\*/', ' ', src, flags=re.S)
    src = re.sub(r'//[^\n]*', ' ', src)
    # Preprocessor lines are not statements; left in, the directives above a
    # definition get absorbed into it and the definition is skipped.
    src = re.sub(r'^[ \t]*#.*(?:\\\n.*)*$', ' ', src, flags=re.M)

    out, seen = [], []
    for st in statements(src):
        if 'g_warthog_' not in st:
            continue
        flat = ' '.join(st.split())
        if re.match(r'^(extern|static|typedef)\b', flat):
            continue
        decl = flat.split('=', 1)[0]
        if '(' in decl:                      # a prototype, not storage
            continue
        if not re.match(r'^[A-Za-z_]', flat):
            continue
        out.append(flat + ';')
        seen += re.findall(r'\bg_warthog_[A-Za-z0-9_]+', decl)

    # Macros the initialisers reference, so this file stands alone.
    macros, local = [], set()
    for m in re.finditer(r'^[ \t]*#[ \t]*define[ \t]+(WARTHOG_[A-Z0-9_]+)[ \t]+(.+)$',
                         open(at).read(), flags=re.M):
        local.add(m.group(1))
        macros.append('#ifndef %s\n#define %s %s\n#endif' % (m.group(1), m.group(1), m.group(2).strip()))
    # Those from cfg.h (a build's defaults), with the #if around them, so this file follows the flags.
    used = set(re.findall(r'\b(WARTHOG_[A-Z0-9_]+)\b', ' '.join(o.split('=', 1)[1] for o in out if '=' in o)))
    macros += cfg_macros(os.path.join(os.path.dirname(at), 'cfg.h'), used - local)

    body = HEADER + '\n'.join(macros) + '\n\n' + '\n'.join(out) + '\n'
    open('warthog_globals.c', 'w').write(body)
    sys.stderr.write('warthog_globals.c: %d statements, %d symbols\n' % (len(out), len(set(seen))))


if __name__ == '__main__':
    main()
