/*
 * GENERATED by gen_warthog_globals.py from main/at.c -- do not edit by hand.
 *
 * Mirrors at.c's definitions of every g_warthog_* object, with at.c's own
 * types and initial values. See the generator for why this is scraped rather
 * than written out by hand.
 */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* ESP-IDF puts a couple of these in RTC memory that survives deep sleep. The
 * host has no such thing and ordinary .bss is the truthful stand-in. */
#define RTC_NOINIT_ATTR

#ifndef WARTHOG_VERSION
#define WARTHOG_VERSION "0.0.0"
#endif
#ifndef WARTHOG_MESH_HOST_CCMP_DEFAULT_ON
#define WARTHOG_MESH_HOST_CCMP_DEFAULT_ON 0
#endif
#ifndef WARTHOG_RSSI_PEERS
#define WARTHOG_RSSI_PEERS 6
#endif

volatile uint32_t g_warthog_usb_tx_sent = 0, g_warthog_usb_tx_dropped = 0;
volatile uint32_t g_warthog_rxtap_total = 0;
volatile uint32_t g_warthog_rxtap_mgmt = 0;
volatile uint32_t g_warthog_rxtap_beacon = 0;
volatile uint16_t g_warthog_rxtap_last_fc = 0;
volatile uint8_t g_warthog_rxtap_last_ta[6] = { 0 };
volatile uint32_t g_warthog_bcn_req = 0;
volatile uint32_t g_warthog_bcn_served = 0;
volatile uint32_t g_warthog_bcn_null = 0;
volatile uint32_t g_warthog_bcn_enq_ok = 0;
volatile uint32_t g_warthog_bcn_enq_err = 0;
volatile uint32_t g_warthog_bcn_txcomp = 0;
volatile uint32_t g_warthog_bcn_inactive = 0;
volatile uint32_t g_warthog_prsp_rx = 0;
volatile uint32_t g_warthog_prsp_tx = 0;
volatile uint32_t g_warthog_prsp_fail = 0;
volatile uint8_t g_warthog_prsp_last_da[6] = { 0 };
volatile uint8_t g_warthog_bcn_own[160] = { 0 };
volatile uint16_t g_warthog_bcn_own_len = 0;
volatile uint8_t g_warthog_bcn_rx_frame[160] = { 0 };
volatile uint16_t g_warthog_bcn_rx_len = 0;
volatile uint8_t g_warthog_prq_frame[96] = { 0 };
volatile uint16_t g_warthog_prq_len = 0;
volatile uint8_t g_warthog_prq_ta[6] = { 0 };
volatile uint32_t g_warthog_prq_named = 0;
volatile uint32_t g_warthog_prq_offer = 0;
volatile uint8_t g_warthog_plink_tx[192] = { 0 };
volatile uint16_t g_warthog_plink_tx_len = 0;
volatile uint16_t g_warthog_plink_tx_full = 0;
volatile uint8_t g_warthog_plink_rx[192] = { 0 };
volatile uint16_t g_warthog_plink_rx_len = 0;
volatile uint16_t g_warthog_plink_rx_full = 0;
volatile uint32_t g_warthog_host_ccmp_on = WARTHOG_MESH_HOST_CCMP_DEFAULT_ON;
volatile uint32_t g_warthog_swccmp_tried = 0;
volatile uint32_t g_warthog_swccmp_tx_ok = 0;
volatile uint32_t g_warthog_swccmp_tx_fail = 0;
volatile uint32_t g_warthog_swccmp_ok = 0;
volatile uint32_t g_warthog_swccmp_micfail = 0;
volatile uint32_t g_warthog_swccmp_nokey = 0;
volatile uint32_t g_warthog_swccmp_grpkey = 0;
volatile uint32_t g_warthog_swccmp_badhdr = 0;
volatile uint32_t g_warthog_swccmp_short = 0;
volatile uint32_t g_warthog_swccmp_last_keyid = 0;
volatile uint32_t g_warthog_swccmp_last_aadlen = 0;
volatile uint8_t g_warthog_swccmp_last_aad[32] = { 0 };
volatile uint32_t g_warthog_mpm_tx_conv = 0;
volatile uint32_t g_warthog_mpm_rx_conv = 0;
volatile uint32_t g_warthog_mpm_rx = 0;
volatile uint32_t g_warthog_mpm_open_tx = 0;
volatile uint32_t g_warthog_mpm_conf_tx = 0;
volatile uint32_t g_warthog_mpm_conf_rx = 0;
volatile uint32_t g_warthog_mpm_close_rx = 0;
volatile uint32_t g_warthog_mpm_parse_fail = 0;
volatile uint32_t g_warthog_mpm_our_llid = 0;
volatile uint32_t g_warthog_mpm_our_plid = 0;
volatile uint8_t g_warthog_mpm_dump[96];
volatile uint16_t g_warthog_mpm_dump_len = 0;
volatile uint16_t g_warthog_mpm_dump_full = 0;
volatile uint32_t g_warthog_mpm_close_reason = 0;
volatile uint32_t g_warthog_mpm_estab = 0;
volatile uint32_t g_warthog_mesh_peer_add_fail = 0;
volatile uint32_t g_warthog_mesh_chip_sta_fail = 0;
volatile uint32_t g_warthog_mesh_key_fail = 0;
volatile uint32_t g_warthog_mesh_secure = 1;
volatile uint32_t g_warthog_mesh_fwd = 0, g_warthog_mesh_bridge = 0, g_warthog_mesh_grp = 0;
volatile uint32_t g_warthog_mesh_pmf = 0;
volatile uint32_t g_warthog_fwd_uni = 0, g_warthog_fwd_grp = 0, g_warthog_fwd_nomem = 0;
volatile uint32_t g_warthog_fwd_drop_own = 0, g_warthog_fwd_drop_dup = 0, g_warthog_fwd_drop_ttl = 0;
volatile uint32_t g_warthog_fwd_drop_nopath = 0, g_warthog_fwd_drop_nofwd = 0, g_warthog_fwd_drop_bad = 0;
volatile uint32_t g_warthog_fwd_perr_tx = 0, g_warthog_fwd_preq_tx = 0;
volatile uint32_t g_warthog_hwmp_relay_preq = 0, g_warthog_hwmp_relay_prep = 0, g_warthog_hwmp_relay_perr = 0;
volatile uint32_t g_warthog_fwd_perr_suppressed = 0, g_warthog_fwd_drop_full = 0;
volatile uint32_t g_warthog_fwd_pend_tx = 0, g_warthog_fwd_pend_drop = 0, g_warthog_hwmp_prot = 0;
volatile uint32_t g_warthog_hwmp_unprotected = 0, g_warthog_hwmp_mmie = 0, g_warthog_hwmp_nommie = 0;
volatile uint32_t g_warthog_rxtap_data = 0;
volatile uint32_t g_warthog_rx_data_stad_hit = 0;
volatile uint32_t g_warthog_rx_data_stad_miss = 0;
volatile uint8_t g_warthog_rx_data_miss_ta[6] = { 0 };
volatile uint32_t g_warthog_rx_data_delivered = 0;
volatile uint32_t g_warthog_tx_data_enq = 0;
volatile uint32_t g_warthog_tx_data_deq = 0;
volatile uint32_t g_warthog_tx_data_hdr = 0;
volatile uint32_t g_warthog_tx_drv_ok = 0;
volatile uint32_t g_warthog_tx_drv_err = 0;
volatile int32_t g_warthog_tx_drv_last_err = 0;
volatile uint32_t g_warthog_txst_total = 0;
volatile uint32_t g_warthog_txst_acked = 0;
volatile uint32_t g_warthog_txst_noack = 0;
volatile uint32_t g_warthog_txst_unsent = 0;
volatile uint32_t g_warthog_txst_last_flags = 0;
volatile uint32_t g_warthog_tx_protected = 0;
volatile uint32_t g_warthog_tx_nokey = 0;
volatile uint32_t g_warthog_tx_last_key = 0;
volatile uint32_t g_warthog_txst_data_total = 0;
volatile uint32_t g_warthog_txst_data_acked = 0;
volatile uint32_t g_warthog_txst_data_noack = 0;
volatile uint32_t g_warthog_txst_data_unsent = 0;
volatile uint32_t g_warthog_txst_data_last_flags = 0;
volatile uint32_t g_warthog_shim_rx = 0, g_warthog_shim_rx_notrunning = 0;
volatile uint32_t g_warthog_rx_meshctrl_stripped = 0;
volatile uint32_t g_warthog_rx_meshctrl_ae = 0;
volatile uint32_t g_warthog_rx_fwd_candidate = 0;
volatile uint8_t g_warthog_rx_fwd_last_da[6] = {0};
volatile uint32_t g_warthog_mesh_seq = 0;
volatile uint32_t g_warthog_nodec_group = 0, g_warthog_nodec_fc = 0, g_warthog_nodec_keyid = 0;
volatile uint32_t g_warthog_nodec_group_n = 0, g_warthog_nodec_uni_n = 0;
volatile uint8_t g_warthog_nodec_ta[6];
volatile uint32_t g_warthog_tx_bcast_dup = 0, g_warthog_tx_bcast_copy_fail = 0;
volatile uint32_t g_warthog_keyinst[8];
volatile uint32_t g_warthog_keyinst_n = 0;
volatile uint8_t g_warthog_mesh_self_addr[6];
volatile uint32_t g_warthog_peer_fp[4], g_warthog_peer_mac[4];
volatile uint32_t g_warthog_rekey_req = 0, g_warthog_rekey_done = 0, g_warthog_rekey_aid = 0;
volatile uint32_t g_warthog_mesh_repeer_req = 0;
volatile uint32_t g_warthog_s1g_bcn_rx = 0, g_warthog_s1g_bcn_ours = 0, g_warthog_s1g_bcn_new = 0;
volatile uint32_t g_warthog_s1g_bcn_retry = 0;
volatile uint8_t g_warthog_s1g_bcn_sa[6];
volatile uint32_t g_warthog_bcn_peer_rx = 0;
volatile uint32_t g_warthog_ccmp_kat_ok = 0, g_warthog_ccmp_kat_ran = 0;
volatile uint32_t g_warthog_ccmp_kat_fail_stage = 0;
volatile uint32_t g_warthog_aes_ns_per_block = 0, g_warthog_ccmp_us_per_frame = 0;
volatile uint32_t g_warthog_mbedtls_us_per_frame = 0;
volatile uint32_t g_warthog_aes_setup_ns = 0, g_warthog_aes_ecb_ns = 0;
volatile uint32_t g_warthog_aes_ctr_us = 0;
volatile uint32_t g_warthog_bulk_ccm_us = 0;
volatile uint32_t g_warthog_cryptohost_req = 0, g_warthog_cryptohost_done = 0;
volatile uint32_t g_warthog_cryptohost_rc = 0, g_warthog_cryptohost_val = 0xffffffffu;
volatile uint32_t g_warthog_mpm_close_tx = 0;
volatile uint32_t g_warthog_mpm_expired = 0;
volatile uint32_t g_warthog_mpm_no_slot = 0;
volatile char g_warthog_mpm_links[256] = "(none) ";
volatile uint16_t g_warthog_fc_ring[32];
volatile uint32_t g_warthog_fc_ring_idx = 0;
volatile uint32_t g_warthog_rxdrop_reason = 0, g_warthog_rxdrop_count = 0;
volatile uint32_t g_warthog_reord_outdated = 0;
volatile uint32_t g_warthog_reord_buffered = 0;
volatile uint32_t g_warthog_reord_released = 0;
volatile uint32_t g_warthog_reord_bypass = 0;
volatile uint32_t g_warthog_reord_last_seq = 0;
volatile uint32_t g_warthog_reord_last_exp = 0;
volatile uint32_t g_warthog_filt_reason = 0, g_warthog_filt_drop = 0;
volatile uint32_t g_warthog_filt_hist[9] = { 0 };
volatile uint32_t g_warthog_hwmp_rx = 0, g_warthog_hwmp_preq_rx = 0, g_warthog_hwmp_preq_tx = 0;
volatile uint32_t g_warthog_hwmp_prep_tx = 0, g_warthog_hwmp_parse_fail = 0;
volatile uint32_t g_warthog_hwmp_not_ours = 0;
volatile uint32_t g_warthog_hwmp_prep_rx = 0;
volatile uint32_t g_warthog_ampe_mtk_installed = 0, g_warthog_ampe_mgtk_installed = 0;
volatile uint32_t g_warthog_sae_init = 0;
volatile uint32_t g_warthog_sae_peer_offers = 0, g_warthog_sae_peer_parse_fail = 0;
volatile uint32_t g_warthog_sae_mlme_tx = 0, g_warthog_sae_mlme_auth_tx = 0;
volatile unsigned int g_warthog_sae_addpeer_null = 0, g_warthog_sae_addpeer_ok = 0;
volatile unsigned int g_warthog_sae_authsta_fail = 0, g_warthog_sae_authsta_ok = 0;
volatile uint32_t g_warthog_sae_rates_synth = 0;
volatile uint32_t g_warthog_sae_peer_authproto = 0;
volatile uint32_t g_warthog_sae_peer_authval = 0xff;
volatile unsigned int g_warthog_addp_r_crowded = 0, g_warthog_addp_r_exists = 0;
volatile unsigned int g_warthog_addp_r_addfail = 0, g_warthog_addp_r_rates = 0;
volatile uint32_t g_warthog_sae_sta_add_ok = 0, g_warthog_sae_sta_add_fail = 0;
volatile uint32_t g_warthog_rx_auth = 0;
volatile uint32_t g_warthog_rx_auth_router = 0, g_warthog_rx_auth_other = 0;
volatile uint32_t g_warthog_a3fix_en = 0;
volatile unsigned int g_warthog_sae_hdl_auth = 0, g_warthog_sae_hdl_sae = 0;
volatile unsigned int g_warthog_sae_rx_trans = 0, g_warthog_sae_rx_status = 0;
volatile unsigned int g_warthog_sae_state_now = 0, g_warthog_sae_state_seen = 0;
volatile unsigned int g_warthog_sae_confirm_tx = 0;
volatile unsigned int g_warthog_sae_tx_status = 0, g_warthog_sae_alg_reject = 0;
volatile unsigned int g_warthog_sae_keymgmt = 0, g_warthog_sae_wpa = 0;
volatile unsigned int g_warthog_sae_txfail = 0, g_warthog_sae_txfail_last = 0;
volatile unsigned int g_warthog_sae_rxfail_sa = 0;
volatile unsigned int g_warthog_sae_rx_sa = 0, g_warthog_sae_rx_da = 0;
volatile uint32_t g_warthog_sae_offer_addr = 0;
volatile unsigned int g_warthog_mpm_act_rx = 0, g_warthog_mpm_act_tx = 0;
volatile unsigned int g_warthog_mpm_plink = 0, g_warthog_mpm_plink_seen = 0;
volatile unsigned int g_warthog_hostap_estab = 0, g_warthog_mpm_fsm = 0;
volatile unsigned int g_warthog_accept = 0, g_warthog_accept_nosm = 0, g_warthog_ampe_start = 0;
volatile unsigned int g_warthog_rx_selfprot = 0, g_warthog_rx_action_any = 0;
volatile unsigned int g_warthog_evt_action = 0, g_warthog_evt_mgmt = 0;
volatile unsigned int g_warthog_mesh_act_oversize = 0;
RTC_NOINIT_ATTR volatile uint32_t g_warthog_sae_stage;
volatile uint32_t g_warthog_sae_bridge_en = 1;
volatile uint8_t g_warthog_hwmp_dump[48];
volatile uint16_t g_warthog_hwmp_dump_len = 0, g_warthog_hwmp_dump_full = 0;
volatile uint8_t g_warthog_rxdata_head[64];
volatile uint16_t g_warthog_rxdata_head_len = 0;
volatile uint32_t g_warthog_ccmp_last_keyid = 0, g_warthog_ccmp_blank = 0, g_warthog_ccmp_last_pn = 0, g_warthog_ccmp_replay = 0;
volatile uint32_t g_warthog_rxframe_entry = 0, g_warthog_filter_entry = 0;
volatile uint32_t g_warthog_rxchan_pages = 0, g_warthog_rxchan_data = 0, g_warthog_rxchan_beacon = 0, g_warthog_rxchan_mgmt = 0, g_warthog_rxchan_cmd = 0, g_warthog_rxchan_txstat = 0, g_warthog_rxchan_last = 0;
