#
# Copyright 2022-2023 Morse Micro
#
# SPDX-License-Identifier: Apache-2.0
#

ifneq ($(IP_STACK),lwip)
$(error IP_STACK must be set to lwip if including lwip.mk)
endif

LWIP_DIR = src/lwip

LWIP_SRCS_C += port/arch/sys_arch.c
LWIP_SRCS_C += src/apps/snmp/snmp_asn1.c
LWIP_SRCS_C += src/apps/snmp/snmp_core.c
LWIP_SRCS_C += src/apps/snmp/snmp_mib2.c
LWIP_SRCS_C += src/apps/snmp/snmp_mib2_icmp.c
LWIP_SRCS_C += src/apps/snmp/snmp_mib2_interfaces.c
LWIP_SRCS_C += src/apps/snmp/snmp_mib2_ip.c
LWIP_SRCS_C += src/apps/snmp/snmp_mib2_snmp.c
LWIP_SRCS_C += src/apps/snmp/snmp_mib2_system.c
LWIP_SRCS_C += src/apps/snmp/snmp_mib2_tcp.c
LWIP_SRCS_C += src/apps/snmp/snmp_mib2_udp.c
LWIP_SRCS_C += src/apps/snmp/snmp_msg.c
LWIP_SRCS_C += src/apps/snmp/snmp_netconn.c
LWIP_SRCS_C += src/apps/snmp/snmp_pbuf_stream.c
LWIP_SRCS_C += src/apps/snmp/snmp_raw.c
LWIP_SRCS_C += src/apps/snmp/snmp_scalar.c
LWIP_SRCS_C += src/apps/snmp/snmp_snmpv2_framework.c
LWIP_SRCS_C += src/apps/snmp/snmp_snmpv2_usm.c
LWIP_SRCS_C += src/apps/snmp/snmp_table.c
LWIP_SRCS_C += src/apps/snmp/snmp_threadsync.c
LWIP_SRCS_C += src/apps/snmp/snmp_traps.c
LWIP_SRCS_C += src/apps/snmp/snmpv3.c
LWIP_SRCS_C += src/apps/snmp/snmpv3_mbedtls.c
LWIP_SRCS_C += src/apps/netbiosns/netbiosns.c
LWIP_SRCS_C += src/apps/mdns/mdns.c
LWIP_SRCS_C += src/apps/sntp/sntp.c
LWIP_SRCS_C += src/apps/lwiperf/lwiperf.c
LWIP_SRCS_C += src/apps/mqtt/mqtt.c
LWIP_SRCS_C += src/apps/smtp/smtp.c
LWIP_SRCS_C += src/apps/altcp_tls/altcp_tls_mbedtls.c
LWIP_SRCS_C += src/apps/altcp_tls/altcp_tls_mbedtls_mem.c
LWIP_SRCS_C += src/apps/http/httpd.c
LWIP_SRCS_C += src/apps/http/fs.c
LWIP_SRCS_C += src/netif/ethernet.c
LWIP_SRCS_C += src/api/api_lib.c
LWIP_SRCS_C += src/api/api_msg.c
LWIP_SRCS_C += src/api/err.c
LWIP_SRCS_C += src/api/if_api.c
LWIP_SRCS_C += src/api/netbuf.c
LWIP_SRCS_C += src/api/netdb.c
LWIP_SRCS_C += src/api/netifapi.c
LWIP_SRCS_C += src/api/sockets.c
LWIP_SRCS_C += src/api/tcpip.c
LWIP_SRCS_C += src/core/ipv6/dhcp6.c
LWIP_SRCS_C += src/core/ipv6/ethip6.c
LWIP_SRCS_C += src/core/ipv6/icmp6.c
LWIP_SRCS_C += src/core/ipv6/inet6.c
LWIP_SRCS_C += src/core/ipv6/ip6.c
LWIP_SRCS_C += src/core/ipv6/ip6_addr.c
LWIP_SRCS_C += src/core/ipv6/ip6_frag.c
LWIP_SRCS_C += src/core/ipv6/mld6.c
LWIP_SRCS_C += src/core/ipv6/nd6.c
LWIP_SRCS_C += src/core/ipv4/acd.c
LWIP_SRCS_C += src/core/ipv4/autoip.c
LWIP_SRCS_C += src/core/ipv4/dhcp.c
LWIP_SRCS_C += src/core/ipv4/etharp.c
LWIP_SRCS_C += src/core/ipv4/icmp.c
LWIP_SRCS_C += src/core/ipv4/igmp.c
LWIP_SRCS_C += src/core/ipv4/ip4.c
LWIP_SRCS_C += src/core/ipv4/ip4_addr.c
LWIP_SRCS_C += src/core/ipv4/ip4_frag.c
LWIP_SRCS_C += src/core/altcp.c
LWIP_SRCS_C += src/core/altcp_alloc.c
LWIP_SRCS_C += src/core/altcp_tcp.c
LWIP_SRCS_C += src/core/def.c
LWIP_SRCS_C += src/core/dns.c
LWIP_SRCS_C += src/core/inet_chksum.c
LWIP_SRCS_C += src/core/init.c
LWIP_SRCS_C += src/core/ip.c
LWIP_SRCS_C += src/core/mem.c
LWIP_SRCS_C += src/core/memp.c
LWIP_SRCS_C += src/core/netif.c
LWIP_SRCS_C += src/core/pbuf.c
LWIP_SRCS_C += src/core/raw.c
LWIP_SRCS_C += src/core/stats.c
LWIP_SRCS_C += src/core/sys.c
LWIP_SRCS_C += src/core/tcp.c
LWIP_SRCS_C += src/core/tcp_in.c
LWIP_SRCS_C += src/core/tcp_out.c
LWIP_SRCS_C += src/core/timeouts.c
LWIP_SRCS_C += src/core/udp.c

LWIP_SRCS_H += port/lwipopts.h
LWIP_SRCS_H += port/arch/cc.h
LWIP_SRCS_H += port/arch/sys_arch.h
LWIP_SRCS_H += src/apps/snmp/snmpv3_priv.h
LWIP_SRCS_H += src/apps/snmp/snmp_core_priv.h
LWIP_SRCS_H += src/apps/snmp/snmp_pbuf_stream.h
LWIP_SRCS_H += src/apps/snmp/snmp_asn1.h
LWIP_SRCS_H += src/apps/snmp/snmp_msg.h
LWIP_SRCS_H += src/apps/http/httpd_structs.h
LWIP_SRCS_H += src/apps/altcp_tls/altcp_tls_mbedtls_mem.h
LWIP_SRCS_H += src/apps/altcp_tls/altcp_tls_mbedtls_structs.h
LWIP_SRCS_H += src/include/lwip/ip4_frag.h
LWIP_SRCS_H += src/include/lwip/ip6.h
LWIP_SRCS_H += src/include/lwip/apps/snmpv3.h
LWIP_SRCS_H += src/include/lwip/apps/snmp_mib2.h
LWIP_SRCS_H += src/include/lwip/apps/netbiosns_opts.h
LWIP_SRCS_H += src/include/lwip/apps/altcp_tls_mbedtls_opts.h
LWIP_SRCS_H += src/include/lwip/apps/sntp_opts.h
LWIP_SRCS_H += src/include/lwip/apps/smtp.h
LWIP_SRCS_H += src/include/lwip/apps/snmp_opts.h
LWIP_SRCS_H += src/include/lwip/apps/http_client.h
LWIP_SRCS_H += src/include/lwip/apps/snmp_threadsync.h
LWIP_SRCS_H += src/include/lwip/apps/mdns.h
LWIP_SRCS_H += src/include/lwip/apps/mqtt_priv.h
LWIP_SRCS_H += src/include/lwip/apps/lwiperf.h
LWIP_SRCS_H += src/include/lwip/apps/snmp_table.h
LWIP_SRCS_H += src/include/lwip/apps/mqtt_opts.h
LWIP_SRCS_H += src/include/lwip/apps/snmp_scalar.h
LWIP_SRCS_H += src/include/lwip/apps/mqtt.h
LWIP_SRCS_H += src/include/lwip/apps/snmp_snmpv2_usm.h
LWIP_SRCS_H += src/include/lwip/apps/netbiosns.h
LWIP_SRCS_H += src/include/lwip/apps/smtp_opts.h
LWIP_SRCS_H += src/include/lwip/apps/altcp_proxyconnect.h
LWIP_SRCS_H += src/include/lwip/apps/sntp.h
LWIP_SRCS_H += src/include/lwip/apps/fs.h
LWIP_SRCS_H += src/include/lwip/apps/tftp_common.h
LWIP_SRCS_H += src/include/lwip/apps/tftp_opts.h
LWIP_SRCS_H += src/include/lwip/apps/tftp_server.h
LWIP_SRCS_H += src/include/lwip/apps/httpd_opts.h
LWIP_SRCS_H += src/include/lwip/apps/httpd.h
LWIP_SRCS_H += src/include/lwip/apps/mdns_domain.h
LWIP_SRCS_H += src/include/lwip/apps/mdns_priv.h
LWIP_SRCS_H += src/include/lwip/apps/mdns_opts.h
LWIP_SRCS_H += src/include/lwip/apps/mdns_out.h
LWIP_SRCS_H += src/include/lwip/apps/snmp_core.h
LWIP_SRCS_H += src/include/lwip/apps/snmp_snmpv2_framework.h
LWIP_SRCS_H += src/include/lwip/apps/snmp.h
LWIP_SRCS_H += src/include/lwip/tcpip.h
LWIP_SRCS_H += src/include/lwip/if_api.h
LWIP_SRCS_H += src/include/lwip/icmp.h
LWIP_SRCS_H += src/include/lwip/ip.h
LWIP_SRCS_H += src/include/lwip/altcp_tcp.h
LWIP_SRCS_H += src/include/lwip/memp.h
LWIP_SRCS_H += src/include/lwip/sio.h
LWIP_SRCS_H += src/include/lwip/stats.h
LWIP_SRCS_H += src/include/lwip/pbuf.h
LWIP_SRCS_H += src/include/lwip/sockets.h
LWIP_SRCS_H += src/include/lwip/ip4.h
LWIP_SRCS_H += src/include/lwip/mld6.h
LWIP_SRCS_H += src/include/lwip/errno.h
LWIP_SRCS_H += src/include/lwip/arch.h
LWIP_SRCS_H += src/include/lwip/netif.h
LWIP_SRCS_H += src/include/lwip/mem.h
LWIP_SRCS_H += src/include/lwip/ethip6.h
LWIP_SRCS_H += src/include/lwip/timeouts.h
LWIP_SRCS_H += src/include/lwip/inet.h
LWIP_SRCS_H += src/include/lwip/netdb.h
LWIP_SRCS_H += src/include/lwip/debug.h
LWIP_SRCS_H += src/include/lwip/def.h
LWIP_SRCS_H += src/include/lwip/ip_addr.h
LWIP_SRCS_H += src/include/lwip/altcp_tls.h
LWIP_SRCS_H += src/include/lwip/ip6_addr.h
LWIP_SRCS_H += src/include/lwip/tcpbase.h
LWIP_SRCS_H += src/include/lwip/altcp.h
LWIP_SRCS_H += src/include/lwip/err.h
LWIP_SRCS_H += src/include/lwip/netifapi.h
LWIP_SRCS_H += src/include/lwip/opt.h
LWIP_SRCS_H += src/include/lwip/igmp.h
LWIP_SRCS_H += src/include/lwip/ip6_zone.h
LWIP_SRCS_H += src/include/lwip/ip4_addr.h
LWIP_SRCS_H += src/include/lwip/inet_chksum.h
LWIP_SRCS_H += src/include/lwip/etharp.h
LWIP_SRCS_H += src/include/lwip/priv/mem_priv.h
LWIP_SRCS_H += src/include/lwip/priv/raw_priv.h
LWIP_SRCS_H += src/include/lwip/priv/tcpip_priv.h
LWIP_SRCS_H += src/include/lwip/priv/altcp_priv.h
LWIP_SRCS_H += src/include/lwip/priv/tcp_priv.h
LWIP_SRCS_H += src/include/lwip/priv/memp_std.h
LWIP_SRCS_H += src/include/lwip/priv/nd6_priv.h
LWIP_SRCS_H += src/include/lwip/priv/memp_priv.h
LWIP_SRCS_H += src/include/lwip/priv/sockets_priv.h
LWIP_SRCS_H += src/include/lwip/priv/api_msg.h
LWIP_SRCS_H += src/include/lwip/udp.h
LWIP_SRCS_H += src/include/lwip/icmp6.h
LWIP_SRCS_H += src/include/lwip/dhcp.h
LWIP_SRCS_H += src/include/lwip/init.h
LWIP_SRCS_H += src/include/lwip/autoip.h
LWIP_SRCS_H += src/include/lwip/nd6.h
LWIP_SRCS_H += src/include/lwip/dns.h
LWIP_SRCS_H += src/include/lwip/sys.h
LWIP_SRCS_H += src/include/lwip/tcp.h
LWIP_SRCS_H += src/include/lwip/prot/acd.h
LWIP_SRCS_H += src/include/lwip/prot/ip6.h
LWIP_SRCS_H += src/include/lwip/prot/icmp.h
LWIP_SRCS_H += src/include/lwip/prot/ip.h
LWIP_SRCS_H += src/include/lwip/prot/iana.h
LWIP_SRCS_H += src/include/lwip/prot/ip4.h
LWIP_SRCS_H += src/include/lwip/prot/mld6.h
LWIP_SRCS_H += src/include/lwip/prot/ieee.h
LWIP_SRCS_H += src/include/lwip/prot/igmp.h
LWIP_SRCS_H += src/include/lwip/prot/etharp.h
LWIP_SRCS_H += src/include/lwip/prot/udp.h
LWIP_SRCS_H += src/include/lwip/prot/icmp6.h
LWIP_SRCS_H += src/include/lwip/prot/dhcp.h
LWIP_SRCS_H += src/include/lwip/prot/autoip.h
LWIP_SRCS_H += src/include/lwip/prot/nd6.h
LWIP_SRCS_H += src/include/lwip/prot/dns.h
LWIP_SRCS_H += src/include/lwip/prot/tcp.h
LWIP_SRCS_H += src/include/lwip/prot/ethernet.h
LWIP_SRCS_H += src/include/lwip/prot/dhcp6.h
LWIP_SRCS_H += src/include/lwip/ip6_frag.h
LWIP_SRCS_H += src/include/lwip/netbuf.h
LWIP_SRCS_H += src/include/lwip/raw.h
LWIP_SRCS_H += src/include/lwip/api.h
LWIP_SRCS_H += src/include/lwip/dhcp6.h
LWIP_SRCS_H += src/include/lwip/snmp.h
LWIP_SRCS_H += src/include/netif/lowpan6_common.h
LWIP_SRCS_H += src/include/netif/zepif.h
LWIP_SRCS_H += src/include/netif/lowpan6.h
LWIP_SRCS_H += src/include/netif/bridgeif_opts.h
LWIP_SRCS_H += src/include/netif/lowpan6_opts.h
LWIP_SRCS_H += src/include/netif/lowpan6_ble.h
LWIP_SRCS_H += src/include/netif/bridgeif.h
LWIP_SRCS_H += src/include/netif/etharp.h
LWIP_SRCS_H += src/include/netif/ethernet.h
LWIP_SRCS_H += src/include/netif/ppp/ppp_opts.h
LWIP_SRCS_H += src/include/netif/ppp/ppp_impl.h
LWIP_SRCS_H += src/include/compat/stdc/errno.h
LWIP_SRCS_H += src/include/compat/posix/sys/socket.h
LWIP_SRCS_H += src/include/compat/posix/netdb.h
LWIP_SRCS_H += src/include/compat/posix/net/if.h
LWIP_SRCS_H += src/include/compat/posix/arpa/inet.h

MMIOT_SRCS_C += $(addprefix $(LWIP_DIR)/,$(LWIP_SRCS_C))
MMIOT_SRCS_H += $(addprefix $(LWIP_DIR)/,$(LWIP_SRCS_H))

MMIOT_INCLUDES += $(LWIP_DIR)/src/include
MMIOT_INCLUDES += $(LWIP_DIR)/src/include/compat/posix
MMIOT_INCLUDES += $(LWIP_DIR)/port

CFLAGS-$(LWIP_DIR) += -Wno-unused-parameter

BUILD_DEFINES += LWIP_IPV4=$(MMIPAL_IPV4_ENABLED)
BUILD_DEFINES += LWIP_IPV6=$(MMIPAL_IPV6_ENABLED)

ifneq ($(IP_STACK),lwip)
ifeq ($(ON_DEMAND_TIMERS_ENABLED),1)
$(error ON_DEMAND_TIMERS_ENABLED can only be used with the lwip IP_STACK)
endif
endif
BUILD_DEFINES += MORSE_LWIP_TIMERS_ON_DEMAND=$(ON_DEMAND_TIMERS_ENABLED)

# Enable LWIP statistics and debug
DEBUG_BUILD_DEFINES += LWIP_STATS=1
DEBUG_BUILD_DEFINES += LWIP_DEBUG
DEBUG_BUILD_DEFINES += MEMP_SANITY_CHECK=1
