; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
;
; Copyright 2024-2026 Morse Micro
; SPDX-License-Identifier: Apache-2.0

[platformio]
default_envs = mm-mm6108-ekh05

[env]
; monitor_port allows a specific serial port to be selected for monitoring. This may be useful
; to ensure the correct serial port is selected in cases where more than one is available.
; See https://docs.platformio.org/en/latest/projectconf/sections/env/options/monitor/monitor_port.html
;monitor_port = COM4
;monitor_port = /dev/serial/by-id/usb-STMicroelectronics_ST*

; Set the monitor baudrate. This should not be modified unless a corresponding change is made
; on the device.
monitor_speed = 115200

build_flags =
    ; Optimize builds for size. Changing this may cause flash to overflow
    ; for some example app and platform combinations.
    -Os




custom_mm_iot_components =
    mmconfig
    slip
    mmutils
    littlefs
    freertos-common
    freertos-$(CORE)
    morselib
    morsefirmware
    wpa_supplicant
    mbedtls
    mmipal
    mmpktmem
    $(IP_STACK)
    mmregdb


; This determines the network stack that will be built. Note that freertosplustcp
 ; support is deprecated and will be removed in a future release.
; Options:
; - lwip
; - freertosplustcp
custom_ip_stack = lwip

; This enables/disables IPv4 support.
; Options:
; - 0
; - 1
custom_mmipal_ipv4_enabled = 1

; This enables/disables IPv6 support.
; Options:
; - 0
; - 1
custom_mmipal_ipv6_enabled = 0

[env:mm-mm6108-ekh05]
platform = mm_iottoolkit
framework = mm_iot
board = mm-mm6108-ekh05

[env:mm-mm6108-ekh05-sdio]
platform = mm_iottoolkit
framework = mm_iot
board = mm-mm6108-ekh05-sdio

[env:mm-ekh08-u575]
platform = mm_iottoolkit
framework = mm_iot
board = mm-ekh08-u575

[env:mm-ekh08-u575-sdio]
platform = mm_iottoolkit
framework = mm_iot
board = mm-ekh08-u575-sdio

[env:mm-ekh08-wb55]
platform = mm_iottoolkit
framework = mm_iot
board = mm-ekh08-wb55

[env:mm-ekh08-wb55-ble]
platform = mm_iottoolkit
framework = mm_iot
board = mm-ekh08-wb55-ble

[env:mm-ekh08-h753]
platform = mm_iottoolkit
framework = mm_iot
board = mm-ekh08-h753

[env:mm-mm8108-ekh05]
platform = mm_iottoolkit
framework = mm_iot
board = mm-mm8108-ekh05

[env:mm-mm8108-ekh05-sdio]
platform = mm_iottoolkit
framework = mm_iot
board = mm-mm8108-ekh05-sdio

[env:mm-ekh18-wb55]
platform = mm_iottoolkit
framework = mm_iot
board = mm-ekh18-wb55
